import type { City } from '@/types/city'
import imgSeoul from '@/img/Nam-June-Paik-TV-Buddha.jpeg'
import imgBerlin from '@/img/Abstraktes Bild-Gerhard Richter.jpg'
import imgLondon from '@/img/BACON_1969_Three_Studies_of_Lucian_Freud_triptych-620x420.jpg'
import imgNewYork from '@/img/Warhol_Marilyn.jpg'
import imgMexicoCity from '@/img/diego-and-i.jpg'
import imgMelbourne from '@/img/First-Class Marksman.jpg'
import imgAmsterdam from '@/img/Untitled XXV.jpg'
import imgBeijing from '@/img/Twelve_Landscape_Screens_by_Qi_Baishi.jpg'
import imgBarcelona from '@/img/Blue-Star-1-796x1024.jpg'
import imgChicago from '@/img/jimson-weed-white-flower.jpg'
import imgDubai from '@/img/farhad-moshiri-14439_0@2x.jpg'
import imgHongKong from '@/img/Juin-Octobre 1985.jpg'
import imgParis from '@/img/FC1 (Fire-Color 1).jpg'
import imgVenice from '@/img/Concetto Spaziale, La Fine di Dio.jpg'
import imgBasel from '@/img/Méta-Malevich.jpg'
import imgTokyo from '@/img/Yayoi Kusama Untitled.jpg'
import imgShanghai from '@/img/Zeng Fanzhi The Last Supper.jpg'
import imgSingapore from '@/img/Still Life with Big Durian.jpg'

/** Sample years for every city's `trend` array — one year per value. */
export const TREND_YEARS = [2000, 2005, 2010, 2015, 2020, 2025] as const

export const cities: readonly City[] = [
  {
    slug: 'seoul', code: 'SEO', name: 'Seoul', nameKo: '서울', country: 'South Korea', latitude: 37.5665, longitude: 126.978,
    index: 78.4, type: 'Networked Experimenter', typeKo: '네트워크형 실험 도시', dna: 'Fast systems · Fluid formats', dnaKo: '빠른 체계 · 유연한 형식',
    insightKo: '빠른 실행 체계와 유연한 형식 실험이 강점입니다. 인터랙티브 오브제 쇼룸과 작가 에디션 상품으로 연결할 수 있습니다.',
    signalScores: { market: 78, cultural: 87, opportunity: 82 },
    market: { artists: ['Lee Bul', 'Haegue Yang'], priceRange: '10K–1.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['MMCA', 'Leeum', 'Seoul Museum of Art'], events: ['Seoul Mediacity Biennale', 'Frieze Seoul'], keywords: ['digital material', 'institutional scale', 'Asian bridge'], keywordsKo: ['디지털 물성', '기관 규모', '아시아 교량'] },
    industry: ['Furniture', 'Hotel', 'Fashion'], industryKo: ['가구', '호텔', '패션'],
    opportunity: 'Interactive object showroom · artist-edition product', opportunityKo: '인터랙티브 오브제 쇼룸 · 작가 에디션 상품', opportunityWhy: '기술 수용 속도가 빠르고 가구·호텔 산업이 밀집해, 체험형 제품화까지의 경로가 짧습니다.',
    location: '한강을 사이에 두고 도심이 둘로 나뉜 대도시이며, 인천공항을 통해 동북아 환승 거점 역할을 합니다. 반도 끝단이라는 조건 탓에 육로 교류보다 항공·해상 네트워크 의존도가 높습니다.',
    heritage: '조선 왕조 500년의 궁궐과 성곽이 고층 시가지와 한 켜에 겹쳐 있습니다. 전쟁으로 도시 대부분이 소실된 뒤 재건되어, 원형이 보존된 유산보다 다시 지어지고 재해석된 유산의 비중이 큽니다.',
    adaptability: '제도와 인프라가 빠르게 바뀌는 대신 축적의 시간이 짧습니다. 새로운 매체와 형식을 시도하기에는 유리하지만, 장기 보존과 아카이브 체계는 상대적으로 얇습니다.',
    outlook: '미디어아트와 기술 기반 전시에서 아시아권 기준을 먼저 세울 여지가 큽니다. 관건은 국제 시장과의 접점을 유지하면서 지역 제작 기반을 함께 키울 수 있는가입니다.',
    trendNote: '2010년대 중반 국제 아트페어 유치와 기관 신설이 겹치며 반등했습니다. 상승분은 시장 규모보다 기관·행사 인프라 확충에서 나왔습니다.',
    trend: [71.2, 73.6, 75.0, 74.1, 76.8, 78.4],
    signatureWork: { title: 'TV 부처', titleOriginal: 'TV Buddha', artist: '백남준', artistOriginal: 'Nam June Paik', year: 1974, note: '18세기 목조 불상과 폐쇄회로 TV가 서로를 마주 보는 비디오 설치 · 백남준의 대표 아이콘', collection: '스테델릭 미술관, 암스테르담', collectionNote: '1974년 원본 · 이후 여러 변주작 제작', commission: '1974 갈레리아 보니노, 뉴욕 초연',
      meaning: '거울보다 왜곡이 적은 카메라와 TV 화면을 통해 불상은 자신을 영원히 응시합니다. 끝없는 자기 응시와 자기 반성이라는 깨달은 자의 속성을 매체의 구조로 옮겨 놓은 것입니다. 동시에 전원을 끊는 순간 꺼져 버리는 TV 화면은 인간 의식의 속성에 대한 비유이기도 합니다.',
      intent: '백남준은 동양의 관조와 서구의 기술을 한자리에 놓고, TV가 수신 장치가 아니라 사유의 도구가 될 수 있는지 물었습니다. 실시간 영상은 편집도 지연도 없이 오직 지금만을 비춥니다.',
      cityLink: '서울에서 태어난 백남준이 동아시아의 불교 도상과 서구 미디어 기술을 하나로 묶은 작업입니다. 전통적 형식과 새 매체를 빠르게 접붙이는 서울의 실험 방식과 그대로 겹칩니다.',
      image: imgSeoul },
  },
  {
    slug: 'berlin', code: 'BER', name: 'Berlin', nameKo: '베를린', country: 'Germany', latitude: 52.52, longitude: 13.405,
    index: 80.2, type: 'Independent Production Lab', typeKo: '독립 제작 실험실', dna: 'Dense production · Open networks', dnaKo: '밀집된 제작 · 열린 네트워크',
    insightKo: '밀도 높은 제작 기반과 열린 네트워크가 축입니다. 순환 소재 레지던시와 커뮤니티 쇼룸이 유효합니다.',
    signalScores: { market: 62, cultural: 91, opportunity: 79 },
    market: { artists: ['Olafur Eliasson', 'Katharina Grosse'], priceRange: '8K–2.0M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Hamburger Bahnhof', 'KW', 'Gropius Bau'], events: ['Berlin Art Week', 'Gallery Weekend'], keywords: ['independent space', 'critical practice', 'reuse'], keywordsKo: ['독립 공간', '비평적 실천', '재사용'] },
    industry: ['Fashion', 'Furniture', 'Urban space'], industryKo: ['패션', '가구', '도시 공간'],
    opportunity: 'Circular-material residency · community showroom', opportunityKo: '순환 소재 레지던시 · 커뮤니티 쇼룸', opportunityWhy: '값싼 대형 작업 공간과 재사용 담론이 이미 자리 잡아 실험을 그대로 사업화할 수 있습니다.',
    location: '분단과 통일을 거치며 도심이 두 개의 중심으로 남았고, 그 틈에 저렴한 대형 공간이 대량으로 생겼습니다. 유럽 대륙 한가운데라는 위치가 인력 유입을 계속 떠받칩니다.',
    heritage: '왕정과 바이마르, 전쟁과 분단의 층이 한 도시에 그대로 쌓여 있습니다. 기념과 반성을 동시에 요구받는 도시라, 유산을 다루는 방식 자체가 논쟁의 대상이 됩니다.',
    adaptability: '임대료와 규제가 비교적 느슨해 실험적 시도가 빨리 자리 잡습니다. 다만 최근 젠트리피케이션으로 작업실이 밀려나면서, 이 개방성이 얼마나 유지될지가 쟁점입니다.',
    outlook: '제작 기반과 비평 담론이 함께 있는 드문 조건이라 중장기 경쟁력이 높습니다. 시장 규모는 파리·런던에 미치지 못하므로 유통 경로 설계가 과제로 남습니다.',
    trendNote: '완만한 우상향이지만 중간에 정체 구간이 있습니다. 기관 활동은 꾸준한 반면 시장 축이 따라오지 못한 시기가 반영된 모양입니다.',
    trend: [76.5, 78.0, 77.2, 79.4, 79.0, 80.2],
    signatureWork: { title: '추상화', titleOriginal: 'Abstraktes Bild', artist: '게르하르트 리히터', artistOriginal: 'Gerhard Richter', year: 1986, priceUsd: '약 4,630만 달러', priceKrw: '약 510억 원', note: '스퀴지 기법으로 완성된 독일 현대 미술 거장의 대작', auction: '2015 소더비 런던',
      meaning: '스퀴지로 물감층을 밀어내 우연과 통제가 뒤섞인 화면으로, 회화가 무엇을 재현할 수 있는가를 되묻습니다.',
      intent: '사진적 사실주의와 추상을 평생 오가며 이미지의 신뢰성을 의심해 온 작가가, 붓 대신 스퀴지를 써서 결정권의 상당 부분을 우연에 넘긴 결과물입니다.',
      cityLink: '전후 독일 미술이 역사와 이미지를 다루는 방식을 대표합니다. 비판적 실천과 독립 제작 기반이 두터운 베를린 씬이 이 계보를 현재형으로 잇고 있습니다.',
      image: imgBerlin },
  },
  {
    slug: 'london', code: 'LON', name: 'London', nameKo: '런던', country: 'United Kingdom', latitude: 51.5072, longitude: -0.1276,
    index: 88.6, type: 'Global Market Institution', typeKo: '글로벌 시장·기관 중심지', dna: 'Market depth · Institutional reach', dnaKo: '시장의 깊이 · 기관의 영향력',
    insightKo: '시장의 깊이와 기관의 영향력이 함께 작동합니다. 컬처 컨시어지와 컬렉션 기반 브랜드 프로그램에 적합합니다.',
    signalScores: { market: 93, cultural: 88, opportunity: 80 },
    market: { artists: ['Lubaina Himid', 'Damien Hirst'], priceRange: '20K–5.0M+', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Tate Modern', 'Serpentine', 'ICA'], events: ['Frieze London', 'London Gallery Weekend'], keywords: ['global market', 'public institution', 'diaspora'], keywordsKo: ['글로벌 시장', '공공 기관', '디아스포라'] },
    industry: ['Finance', 'Hospitality', 'Fashion'], industryKo: ['금융', '호스피탈리티', '패션'],
    opportunity: 'Cultural concierge · collection-led brand programme', opportunityKo: '컬처 컨시어지 · 컬렉션 기반 브랜드 프로그램', opportunityWhy: '금융 자산과 기관 접근성이 한곳에 모여 있어 고액 고객 대상 서비스 수요가 큽니다.',
    location: '템스강을 축으로 금융지구와 문화지구가 인접해 있어 자본과 예술의 거리가 짧습니다. 영어권 관문이자 대서양과 유럽을 잇는 위치가 인력과 거래를 동시에 끌어들입니다.',
    heritage: '대영박물관을 비롯한 컬렉션 상당수가 제국 시기에 수집되어, 소장품의 기원을 둘러싼 반환 논의가 계속됩니다. 유산의 규모가 클수록 그 출처를 설명할 책임도 커지는 도시입니다.',
    adaptability: '경매와 갤러리 구조가 이미 촘촘해 새 형식도 빠르게 상품화됩니다. 반대로 임대료와 진입 비용이 높아 초기 작가가 자리 잡기는 어려운 편입니다.',
    outlook: '브렉시트 이후 유럽 내 거래 비용이 늘면서 일부 기능이 파리로 이동했습니다. 기관의 무게는 여전하지만 시장 관문으로서의 독점적 지위는 예전만 못합니다.',
    trendNote: '높은 수준에서 소폭 등락을 반복합니다. 이미 상단에 도달한 지표라 추가 상승 여력보다 유지 능력이 관건입니다.',
    trend: [84.0, 85.6, 86.9, 86.2, 87.8, 88.6],
    signatureWork: { title: '루시안 프로이트의 세 가지 습작', titleOriginal: 'Three Studies of Lucian Freud', artist: '프랜시스 베이컨', artistOriginal: 'Francis Bacon', year: 1969, priceUsd: '약 1억 4,240만 달러', priceKrw: '약 1,520억 원', note: '런던 스쿨의 정점이자 삼면화 구성의 기념비적 작품', auction: '2013 크리스티 뉴욕',
      meaning: '친구이자 경쟁자였던 화가 루시안 프로이트를 세 각도에서 포착한 삼면화로, 인간 신체의 취약함과 심리적 압박을 드러냅니다.',
      intent: '베이컨은 가까운 인물을 반복해 그렸고 프로이트와의 우정과 경쟁이 핵심 소재였습니다. 제단화의 삼면 구조를 세속의 초상으로 옮겨 놓았습니다.',
      cityLink: '전후 런던 소호를 거점으로 한 「런던 스쿨」의 상징입니다. 런던이 기관과 시장 양쪽에서 현대미술의 가격과 정전을 동시에 만들어 온 도시임을 보여 줍니다.',
      image: imgLondon },
  },
  {
    slug: 'new-york', code: 'NYC', name: 'New York', nameKo: '뉴욕', country: 'United States', latitude: 40.7128, longitude: -74.006,
    index: 91.4, type: 'Global Market Engine', typeKo: '글로벌 시장 엔진', dna: 'Capital concentration · Network power', dnaKo: '자본 집중 · 네트워크 장악력',
    insightKo: '자본 집중도와 네트워크 영향력이 최상위입니다. 컬렉션 인텔리전스 서비스와 문화 플래그십에 유리합니다.',
    signalScores: { market: 97, cultural: 91, opportunity: 86 },
    market: { artists: ['Julie Mehretu', 'Jean-Michel Basquiat'], priceRange: '25K–10M+', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['MoMA', 'Whitney', 'New Museum'], events: ['The Armory Show', 'Frieze New York'], keywords: ['market liquidity', 'gallery network', 'global influence'], keywordsKo: ['시장 유동성', '갤러리 네트워크', '국제적 영향력'] },
    industry: ['Finance', 'Retail', 'Media'], industryKo: ['금융', '리테일', '미디어'],
    opportunity: 'Collection intelligence service · cultural flagship', opportunityKo: '컬렉션 인텔리전스 서비스 · 문화 플래그십', opportunityWhy: '거래량이 가장 많아 데이터 기반 자문과 브랜드 플래그십 수요가 함께 발생합니다.',
    location: '맨해튼이라는 좁은 섬에 기관·갤러리·경매사가 도보 거리로 밀집해 있습니다. 밀도 자체가 거래 속도를 만들어 내는 구조입니다.',
    heritage: '유럽 이주민이 가져온 모더니즘이 전후 미국에서 재편되며 세계 미술의 중심이 옮겨 온 도시입니다. 역사가 짧은 대신 20세기 미술의 정전 상당 부분이 여기서 만들어졌습니다.',
    adaptability: '새로운 시도를 시장이 곧바로 흡수하지만, 그만큼 상업화 속도도 빠릅니다. 비영리 공간과 작가 작업실이 외곽으로 계속 밀려나는 압력이 상존합니다.',
    outlook: '시장 지배력은 당분간 유지될 전망입니다. 변수는 아시아 시장의 성장 속도와, 높은 생활비가 초기 작가 유입을 언제까지 버텨 주느냐입니다.',
    trendNote: '전 구간에서 완만하게 상승하며 정체가 거의 없습니다. 자본과 네트워크가 동시에 작동하는 도시의 전형적인 형태입니다.',
    trend: [87.0, 88.4, 89.6, 90.1, 90.8, 91.4],
    signatureWork: { title: '샷 세이지 블루 메릴린', titleOriginal: 'Shot Sage Blue Marilyn', artist: '앤디 워홀', artistOriginal: 'Andy Warhol', year: 1964, priceUsd: '약 1억 9,504만 달러', priceKrw: '약 2,500억 원', note: '20세기 미술품 경매 사상 최고가이자 미국 작가 역대 최고 기록', auction: '2022 크리스티 뉴욕',
      meaning: '마릴린 먼로의 홍보 사진을 실크스크린으로 반복해, 대중매체가 만든 이미지와 명성의 덧없음을 함께 드러냅니다.',
      intent: '워홀은 대량 복제 이미지를 미술로 끌어들여 원본성 개념을 해체했습니다. 「샷」이라는 제목은 1964년 팩토리에서 한 방문객이 작품 더미에 총을 쏜 사건에서 유래했습니다.',
      cityLink: '팩토리를 중심으로 한 뉴욕의 상업·미디어 문화가 그대로 재료가 된 작품입니다. 뉴욕이 가진 자본 집중도와 시장 규모를 가장 압축적으로 보여 줍니다.',
      image: imgNewYork },
  },
  {
    slug: 'mexico-city', code: 'MEX', name: 'Mexico City', nameKo: '멕시코시티', country: 'Mexico', latitude: 19.4326, longitude: -99.1332,
    index: 72.1, type: 'Local–Global Generator', typeKo: '로컬–글로벌 생성 도시', dna: 'Material culture · Independent energy', dnaKo: '재료의 문화 · 독립적 에너지',
    insightKo: '재료 문화와 독립적 에너지가 원동력입니다. 메이커 중심 호스피탈리티와 소재 리서치 컬렉션이 어울립니다.',
    signalScores: { market: 68, cultural: 84, opportunity: 77 },
    market: { artists: ['Gabriel Orozco', 'Minerva Cuevas'], priceRange: '5K–900K', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Museo Jumex', 'MUAC', 'Kurimanzutto'], events: ['Zona Maco', 'Material Art Fair'], keywords: ['local material', 'artist-run', 'public life'], keywordsKo: ['지역 재료', '작가 운영 공간', '공공적 삶'] },
    industry: ['Food', 'Tourism', 'Furniture'], industryKo: ['식음료', '관광', '가구'],
    opportunity: 'Maker-led hospitality · material research collection', opportunityKo: '메이커 중심 호스피탈리티 · 소재 리서치 컬렉션', opportunityWhy: '지역 재료와 수공 기술을 저렴하게 확보할 수 있어 제작과 체류를 묶기 유리합니다.',
    location: '호수를 메운 분지 위에 세워진 고산 대도시로, 지반과 물 문제가 도시 계획을 계속 규정합니다. 북미와 라틴아메리카를 잇는 위치가 인력과 자본의 통로를 만듭니다.',
    heritage: '아스테카 유적 위에 식민 도시가, 그 위에 근대 도시가 겹쳐 있습니다. 벽화 운동 이래 공공 미술이 국가 서사를 만드는 수단으로 쓰여 온 전통이 지금도 강합니다.',
    adaptability: '작가가 직접 운영하는 공간과 저렴한 제작 여건이 실험을 떠받칩니다. 반면 제도적 지원과 시장 규모가 작아 성과가 해외로 유출되기 쉽습니다.',
    outlook: '라틴아메리카 미술의 재평가와 맞물려 국제 수요가 늘고 있습니다. 지역 재료와 제작 기술을 상품화하는 경로를 설계하면 성장 폭이 커집니다.',
    trendNote: '초반 상승 후 한 차례 조정을 거쳐 다시 오릅니다. 국제 아트페어가 정착한 시점과 조정 구간이 겹칩니다.',
    trend: [65.4, 67.8, 69.0, 68.2, 70.6, 72.1],
    signatureWork: { title: '디에고와 나', titleOriginal: 'Diego y yo', artist: '프리다 칼로', artistOriginal: 'Frida Kahlo', year: 1949, priceUsd: '약 3,490만 달러', priceKrw: '약 412억 원', note: '라틴아메리카 미술 사상 최고 경매가를 기록한 자화상', auction: '2021 소더비 뉴욕',
      meaning: '이마에 남편 디에고 리베라의 얼굴이 떠 있고 눈물을 흘리는 자화상으로, 사랑과 고통이 분리되지 않는 상태를 그립니다.',
      intent: '리베라와 배우 마리아 펠릭스의 관계로 괴로워하던 시기에 그렸습니다. 신체적 고통과 결혼 생활은 칼로가 평생 자기 몸을 통해 기록한 주제였습니다.',
      cityLink: '코요아칸의 카사 아술을 중심으로 한 멕시코시티 예술가 공동체에서 태어난 작업입니다. 멕시코 정체성 운동과 라틴아메리카 미술의 국제적 재평가를 함께 상징합니다.',
      image: imgMexicoCity },
  },
  {
    slug: 'melbourne', code: 'MEL', name: 'Melbourne', nameKo: '멜버른', country: 'Australia', latitude: -37.8136, longitude: 144.9631,
    index: 74.8, type: 'Participation Hub', typeKo: '시민 참여 허브', dna: 'Civic access · Distributed culture', dnaKo: '시민 접근성 · 분산된 문화',
    insightKo: '공공 접근성과 분산된 문화 기반이 특징입니다. 동네 단위 아트 루트와 참여형 호텔 프로그램이 맞습니다.',
    signalScores: { market: 66, cultural: 86, opportunity: 74 },
    market: { artists: ['Patricia Piccinini', 'Brook Andrew'], priceRange: '6K–700K', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['NGV', 'ACCA', 'ACMI'], events: ['Melbourne Art Fair', 'RISING'], keywords: ['public participation', 'moving image', 'First Nations'], keywordsKo: ['시민 참여', '영상 매체', '퍼스트 네이션스'] },
    industry: ['Tourism', 'Education', 'Hospitality'], industryKo: ['관광', '교육', '호스피탈리티'],
    opportunity: 'Neighbourhood art route · participatory hotel programme', opportunityKo: '동네 단위 아트 루트 · 참여형 호텔 프로그램', opportunityWhy: '문화 시설이 보행 단위로 흩어져 있어 동선 자체를 상품으로 만들 수 있습니다.',
    location: '격자형 도심과 골목 문화가 공존해 보행 단위로 문화 시설이 흩어져 있습니다. 대륙 남단이라는 고립된 위치가 자체 생태계를 키우는 방향으로 작용했습니다.',
    heritage: '퍼스트 네이션스의 수만 년 문화 위에 19세기 골드러시 도시가 얹힌 구조입니다. 최근 미술관들이 원주민 작가를 상설 컬렉션 중심에 놓으며 서사를 다시 쓰고 있습니다.',
    adaptability: '공공 자금과 시민 참여 프로그램이 두터워 새로운 형식이 제도권에 빠르게 편입됩니다. 다만 국제 시장과의 거리가 멀어 유통은 여전히 제약입니다.',
    outlook: '참여형·공공 프로그램 모델을 수출할 여지가 큽니다. 시장 축을 보완하지 못하면 작가의 해외 이주가 계속될 수 있습니다.',
    trendNote: '꾸준히 오르지만 기울기가 완만합니다. 참여와 기관 지표가 견인하고 시장 축은 거의 움직이지 않은 결과입니다.',
    trend: [70.0, 71.5, 73.0, 72.4, 74.0, 74.8],
    signatureWork: { title: '퍼스트 클래스 마크스맨', titleOriginal: 'First-Class Marksman', artist: '시드니 놀란', artistOriginal: 'Sidney Nolan', year: 1946, priceUsd: '약 390만 달러', priceKrw: '약 51억 원', note: '호주 현대 미술 아이콘 「네드 켈리」 연작 중 개인 소장 핵심작', auction: '2010 멘지스 경매',
      meaning: '검은 사각 투구를 쓴 무법자 네드 켈리가 황량한 호주 풍경 속에 서 있는 장면으로, 식민지 신화를 다시 쓴 연작의 핵심작입니다.',
      intent: '놀란은 켈리를 영웅도 악당도 아닌 양가적 인물로 그려, 호주라는 국가의 자기 서사를 회화로 재구성하려 했습니다.',
      cityLink: '멜버른 하이데에서 제작되었고 빅토리아주가 켈리 이야기의 실제 무대입니다. NGV를 비롯한 멜버른 기관이 호주 미술의 정전을 세우는 과정과 맞물립니다.',
      image: imgMelbourne },
  },
  {
    slug: 'amsterdam', code: 'AMS', name: 'Amsterdam', nameKo: '암스테르담', country: 'Netherlands', latitude: 52.3676, longitude: 4.9041,
    index: 76.3, type: 'Critical Discourse Hub', typeKo: '비평 담론 허브', dna: 'Institutional critique · Public access', dnaKo: '기관 비평 · 공공 접근성',
    insightKo: '기관 비평과 공공 접근성이 중심축입니다. 디자인 리서치 레지던시와 시민 예술 프로그램이 적합합니다.',
    signalScores: { market: 72, cultural: 84, opportunity: 76 },
    market: { artists: ['Rineke Dijkstra', 'Marlene Dumas'], priceRange: '8K–1.8M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Stedelijk Museum', 'EYE Filmmuseum', 'Foam'], events: ['Art Amsterdam', 'UNSEEN'], keywords: ['critical theory', 'photography', 'civic institution'], keywordsKo: ['비평 이론', '사진', '시민 기관'] },
    industry: ['Tech', 'Fashion', 'Hospitality'], industryKo: ['테크', '패션', '호스피탈리티'],
    opportunity: 'Design-research residency · civic art programme', opportunityKo: '디자인 리서치 레지던시 · 시민 예술 프로그램', opportunityWhy: '디자인 교육과 공공 기금이 두터워 리서치형 협업의 비용이 낮습니다.',
    location: '운하망이 도시 구조를 고정해 대규모 개발이 어렵고, 그만큼 기존 건물의 용도 전환이 일상적입니다. 스히폴 공항을 낀 유럽 환승 거점이라는 조건이 국제 교류를 떠받칩니다.',
    heritage: '황금기 회화와 식민 무역의 부가 같은 기관 안에 보존되어 있습니다. 최근 미술관들이 소장품의 식민지적 기원을 전시 서사에 직접 기술하는 방향으로 전환했습니다.',
    adaptability: '공공 기금과 디자인 교육 기반이 두터워 리서치형 작업이 제도적으로 뒷받침됩니다. 도시 규모가 작아 임대료 상승이 곧바로 작업 공간 부족으로 이어집니다.',
    outlook: '디자인과 미술의 경계 작업에서 유럽 내 거점 역할이 강해질 전망입니다. 시장 규모의 한계는 인접 도시와의 분업으로 보완될 가능성이 큽니다.',
    trendNote: '좁은 폭에서 안정적으로 유지됩니다. 급격한 확장보다 기존 기관의 밀도가 지표를 지탱하는 구조입니다.',
    trend: [73.0, 74.2, 75.6, 74.8, 75.9, 76.3],
    signatureWork: { title: '무제 XXV', titleOriginal: 'Untitled XXV', artist: '빌럼 데 쿠닝', artistOriginal: 'Willem de Kooning', year: 1977, priceUsd: '약 6,630만 달러', priceKrw: '약 770억 원', note: '뉴욕 추상표현주의를 이끈 네덜란드 출신 거장의 후기 대형 추상화', auction: '2016 크리스티 뉴욕',
      meaning: '격렬한 붓질이 풍경과 신체 사이를 오가는 후기 추상으로, 물감 자체의 물질성과 속도가 화면을 지배합니다.',
      intent: '네덜란드에서 미국으로 건너가 추상표현주의를 이끈 작가가, 1970년대 롱아일랜드 이주 이후 빛과 물의 감각을 화면에 끌어들인 시기의 작업입니다.',
      cityLink: '로테르담에서 받은 네덜란드식 미술 교육이 기법의 토대가 되었고, 암스테르담 스테델릭 미술관이 그를 유럽에 소개하며 네덜란드 현대미술의 국제적 좌표를 만들었습니다.',
      image: imgAmsterdam },
  },
  {
    slug: 'beijing', code: 'BEI', name: 'Beijing', nameKo: '베이징', country: 'China', latitude: 39.9042, longitude: 116.4074,
    index: 77.9, type: 'State-Institutional Force', typeKo: '국가·기관 주도 도시', dna: 'Scale infrastructure · Cultural power', dnaKo: '규모의 인프라 · 문화적 영향력',
    insightKo: '대규모 인프라와 문화적 영향력이 결합합니다. 기관 파트너십과 동서 문화 교량 역할이 기회입니다.',
    signalScores: { market: 81, cultural: 80, opportunity: 75 },
    market: { artists: ['Ai Weiwei', 'Zhang Huan'], priceRange: '12K–2.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['CAFA Art Museum', '798 Art District', 'UCCA'], events: ['Beijing 798 Art Festival', 'Art Beijing'], keywords: ['state support', 'contemporary scale', 'Eastern canon'], keywordsKo: ['국가 지원', '현대적 규모', '동아시아 정전'] },
    industry: ['Tech', 'Fashion', 'Architecture'], industryKo: ['테크', '패션', '건축'],
    opportunity: 'Institutional partnership · East–West cultural bridge', opportunityKo: '기관 파트너십 · 동서 문화 교량', opportunityWhy: '대형 기관이 자원을 쥐고 있어 개별 거래보다 기관 단위 협업이 실효적입니다.',
    location: '자금성을 중심으로 한 동심원 구조 위에 거대 순환도로가 겹친 계획 도시입니다. 798 같은 공장 지대가 예술 지구로 전환되며 외곽에 제작 거점이 형성됐습니다.',
    heritage: '왕조의 수도로서 축적된 유산과 20세기 정치사의 흔적이 함께 남아 있습니다. 전통 수묵과 현대 미술이 같은 제도 안에서 다뤄진다는 점이 다른 도시와 구별됩니다.',
    adaptability: '국가 주도로 기관과 인프라가 빠르게 조성되는 반면, 표현의 범위는 제도적 조건에 크게 좌우됩니다. 실험의 속도보다 방향이 먼저 정해지는 도시입니다.',
    outlook: '기관 규모와 자본은 계속 커질 전망입니다. 국제적 위상은 시장 지표보다 표현 환경의 개방 정도에 더 크게 좌우될 것입니다.',
    trendNote: '상승과 정체가 번갈아 나타납니다. 정책 주기에 따라 기관 투자가 집중되는 시기와 그렇지 않은 시기가 갈립니다.',
    trend: [74.5, 76.0, 75.2, 77.0, 76.8, 77.9],
    signatureWork: { title: '산수십이조병', titleOriginal: 'Twelve Landscape Screens', artist: '치바이스', artistOriginal: 'Qi Baishi', year: 1925, priceUsd: '약 1억 4,080만 달러', priceKrw: '약 1,933억 원', note: '중국 미술품 사상 최초로 1억 달러를 돌파한 12폭 병풍 수묵화', auction: '2017 폴리옥션 베이징',
      meaning: '열두 폭 병풍에 펼친 산수로, 문인화의 형식을 지키면서도 일상의 풍경과 생명력을 끌어들였습니다.',
      intent: '목수 출신으로 독학한 치바이스는 예순 이후 화풍을 스스로 바꾸는 「쇠년변법」을 감행해, 전통을 따르되 자신의 눈으로 다시 보는 길을 택했습니다.',
      cityLink: '베이징에 정착해 활동하며 중국 근대 회화의 중심이 되었습니다. 국가와 기관이 주도하는 베이징 미술 체계에서 정전의 자리를 차지한 작가입니다.',
      image: imgBeijing },
  },
  {
    slug: 'barcelona', code: 'BCN', name: 'Barcelona', nameKo: '바르셀로나', country: 'Spain', latitude: 41.3851, longitude: 2.1734,
    index: 73.5, type: 'Mediterranean Creative Node', typeKo: '지중해 창작 거점', dna: 'Architecture culture · Grassroots energy', dnaKo: '건축 문화 · 풀뿌리 에너지',
    insightKo: '건축 문화와 풀뿌리 에너지가 공존합니다. 건축–예술 투어와 비디오 아트 베뉴 프로그램이 유효합니다.',
    signalScores: { market: 69, cultural: 82, opportunity: 76 },
    market: { artists: ['Joan Miró', 'Antoni Tàpies'], priceRange: '6K–1.2M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['MACBA', 'Fundació Joan Miró', 'CCCB'], events: ['Art Barcelona', 'Loop Festival'], keywords: ['architecture culture', 'video art', 'grassroots'], keywordsKo: ['건축 문화', '비디오 아트', '풀뿌리'] },
    industry: ['Tourism', 'Fashion', 'Hospitality'], industryKo: ['관광', '패션', '호스피탈리티'],
    opportunity: 'Architecture-art tour · video art venue programme', opportunityKo: '건축–예술 투어 · 비디오 아트 베뉴 프로그램', opportunityWhy: '도시 전체가 건축 자산이라 별도 시설 없이 콘텐츠를 구성할 수 있습니다.',
    location: '지중해와 산지 사이의 좁은 평지에 격자형 확장 구역이 깔려 도시 밀도가 고르게 높습니다. 항구와 국경이 가까워 프랑스·지중해권과의 교류가 일상적입니다.',
    heritage: '모데르니스메 건축이 도시 전체를 사실상 하나의 전시장으로 만들었습니다. 카탈루냐어와 지역 정체성이 문화 정책의 기준선으로 작동합니다.',
    adaptability: '풀뿌리 공간과 축제 문화가 새로운 시도를 빠르게 흡수합니다. 다만 관광 과밀이 도심 문화 공간을 상업 시설로 대체하는 압력이 큽니다.',
    outlook: '건축 자산과 영상 매체를 결합한 프로그램에서 차별화 여지가 큽니다. 관광 의존도를 낮추지 못하면 지역 생태계가 잠식될 위험이 있습니다.',
    trendNote: '중간에 한 차례 하락한 뒤 회복합니다. 관광 급증기에 지역 문화 지표가 눌렸던 구간이 드러납니다.',
    trend: [69.8, 71.0, 72.4, 71.6, 72.9, 73.5],
    signatureWork: { title: '회화 (에투알 블뢰)', titleOriginal: 'Peinture (Étoile Bleue)', artist: '호안 미로', artistOriginal: 'Joan Miró', year: 1927, priceUsd: '약 3,690만 달러', priceKrw: '약 420억 원', note: '카탈루냐 초현실주의 거장의 「꿈의 회화」 시기 결정적 작업', auction: '2012 소더비 런던',
      meaning: '붉은 바탕 위에 푸른 별이 떠 있는 「꿈의 회화」로, 형상을 기호로 환원해 시적인 우주를 만듭니다.',
      intent: '파리 초현실주의 그룹과 교류하며 무의식과 자동기술을 회화의 방법으로 삼았습니다. 재현을 버리고 기호와 여백만으로 화면을 구성하려 했습니다.',
      cityLink: '바르셀로나에서 태어난 작가에게 카탈루냐의 풍토와 언어는 평생의 뿌리였습니다. 몬주익의 호안 미로 재단은 지금도 도시 문화 인프라의 한 축입니다.',
      image: imgBarcelona },
  },
  {
    slug: 'chicago', code: 'CHI', name: 'Chicago', nameKo: '시카고', country: 'United States', latitude: 41.8781, longitude: -87.6298,
    index: 75.2, type: 'Civic Collection Leader', typeKo: '시민 컬렉션 선도 도시', dna: 'Public access · Collection depth', dnaKo: '공공 접근성 · 소장품의 깊이',
    insightKo: '공공 접근성과 소장품의 깊이가 강점입니다. 시민 예술 프로그램과 건축 중심 경험 설계에 적합합니다.',
    signalScores: { market: 74, cultural: 83, opportunity: 72 },
    market: { artists: ['Kerry James Marshall', 'Chris Ware'], priceRange: '10K–2.0M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Art Institute of Chicago', 'MCA Chicago', 'DuSable'], events: ['EXPO Chicago', 'Chicago Architecture Biennial'], keywords: ['civic collection', 'architecture', 'Black artists'], keywordsKo: ['시민 컬렉션', '건축', '흑인 작가'] },
    industry: ['Finance', 'Architecture', 'Education'], industryKo: ['금융', '건축', '교육'],
    opportunity: 'Civic art programme · architecture-led experience', opportunityKo: '시민 예술 프로그램 · 건축 중심 경험 설계', opportunityWhy: '공공 컬렉션과 건축 유산이 시민 접근성 높은 형태로 이미 개방돼 있습니다.',
    location: '미시간호에 면한 평지에 마천루 군이 밀집해 근대 건축의 실험장이 된 도시입니다. 중서부 물류 결절점이라는 조건이 제조 기반과 미술 교육을 함께 키웠습니다.',
    heritage: '대화재 이후 재건 과정에서 근대 건축의 원형이 만들어졌습니다. 시카고 미술관과 부설 학교가 컬렉션과 교육을 한 몸으로 운영해 온 전통이 깊습니다.',
    adaptability: '교육 기관이 두터워 신진 작가가 꾸준히 배출되지만, 상당수가 뉴욕으로 이동합니다. 도시가 인재를 길러 다른 시장에 공급하는 구조에 가깝습니다.',
    outlook: '흑인 작가 서사의 재평가와 건축 자산을 결합한 프로그램이 성장 축이 될 수 있습니다. 시장 축을 보완해야 인재 유출을 늦출 수 있습니다.',
    trendNote: '완만하지만 흔들림이 적습니다. 기관과 교육 기반이 지표를 아래에서 받치는 형태입니다.',
    trend: [72.0, 73.4, 72.8, 74.1, 74.6, 75.2],
    signatureWork: { title: '흰 독말풀 / 백색 꽃 1호', titleOriginal: 'Jimson Weed/White Flower No. 1', artist: '조지아 오키프', artistOriginal: 'Georgia O’Keeffe', year: 1932, priceUsd: '약 4,440만 달러', priceKrw: '약 480억 원', note: 'SAIC 출신 거장 · 전 세계 여성 작가 경매 사상 최고가 기록', auction: '2014 소더비 뉴욕',
      meaning: '독말풀 꽃을 화면 가득 확대해, 스쳐 지나가던 대상을 정면으로 마주 보게 만드는 작품입니다.',
      intent: '아무도 꽃을 제대로 보지 않는다고 여긴 오키프는, 크게 그려서라도 보게 만들겠다는 생각으로 확대 구도를 밀고 나갔습니다.',
      cityLink: '시카고 미술관 부설 학교에서 수학하며 화가의 길을 시작했습니다. 시민 컬렉션과 미술 교육이 두터운 시카고의 기반이 그의 출발점이었습니다.',
      image: imgChicago },
  },
  {
    slug: 'dubai', code: 'DXB', name: 'Dubai', nameKo: '두바이', country: 'UAE', latitude: 25.2048, longitude: 55.2708,
    index: 71.8, type: 'Global Connector Hub', typeKo: '글로벌 연결 허브', dna: 'Capital mobility · East–West bridge', dnaKo: '자본의 이동성 · 동서 교량',
    insightKo: '자본의 이동성과 동서 교량 역할이 핵심입니다. 고액자산가 아트 어드바이저리와 문화 관광 프로그램이 유망합니다.',
    signalScores: { market: 76, cultural: 65, opportunity: 81 },
    market: { artists: ['Etel Adnan', 'Hassan Sharif'], priceRange: '8K–1.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Alserkal Avenue', 'Louvre Abu Dhabi', 'Jameel Arts Centre'], events: ['Art Dubai', 'Dubai Design Week'], keywords: ['free zone culture', 'Middle East bridge', 'ultra-HNW'], keywordsKo: ['자유구역 문화', '중동 교량', '초고액자산가'] },
    industry: ['Hospitality', 'Finance', 'Retail'], industryKo: ['호스피탈리티', '금융', '리테일'],
    opportunity: 'HNW art advisory · cultural tourism programme', opportunityKo: '고액자산가 아트 어드바이저리 · 문화 관광 프로그램', opportunityWhy: '초고액 자산가가 밀집하고 환승 수요가 커서 자문과 관광을 함께 묶을 수 있습니다.',
    location: '사막 위에 계획적으로 세워진 도시로, 유럽·아시아·아프리카를 잇는 항공 환승 거점이라는 위치가 거의 모든 산업의 근거가 됩니다. 알세르칼 같은 창고 지구가 예술 구역으로 전환됐습니다.',
    heritage: '도시 역사가 짧아 축적된 소장품이나 정전이 거의 없습니다. 대신 역내 이주 노동자들이 가져온 다층적 문화가 실질적 유산을 이루고 있습니다.',
    adaptability: '규제와 세제가 유연해 새 기관과 시장이 빠르게 들어섭니다. 축적된 비평 담론이 얇아 시장이 담론보다 앞서 움직이는 경향이 있습니다.',
    outlook: '역내 미술 시장의 관문 역할은 더 커질 전망입니다. 지속 가능성은 자본 유입보다 지역 작가와 기관을 길러 낼 수 있느냐에 달려 있습니다.',
    trendNote: '전 구간에서 가장 가파르게 상승합니다. 낮은 출발점에서 기관과 페어가 동시에 신설된 효과가 그대로 반영됐습니다.',
    trend: [63.0, 66.4, 68.2, 69.5, 70.8, 71.8],
    signatureWork: { title: '에스크 (사랑)', titleOriginal: 'Eshgh (Love)', artist: '파르하드 모시리', artistOriginal: 'Farhad Moshiri', year: 2007, priceUsd: '약 104만 달러', priceKrw: '약 12억 원', note: '중동 현대 미술품 최초로 100만 달러를 돌파한 크리스털 레터링 작업', auction: '2008 보넘스 두바이',
      meaning: '스와로브스키 크리스털로 쓴 페르시아어 「사랑」으로, 장식과 소비문화를 전통 서예의 형식 위에 겹쳐 놓았습니다.',
      intent: '모시리는 이란의 대중문화와 고급 장식 전통을 동시에 인용해, 중동 현대미술이 놓인 상업적 조건 자체를 작품의 재료로 삼았습니다.',
      cityLink: '두바이 경매에서 중동 현대미술 최초로 100만 달러를 넘겼습니다. 두바이가 역내 미술시장 허브로 올라선 전환점을 표시하는 작품입니다.',
      image: imgDubai },
  },
  {
    slug: 'hong-kong', code: 'HKG', name: 'Hong Kong', nameKo: '홍콩', country: 'China SAR', latitude: 22.3193, longitude: 114.1694,
    index: 83.1, type: 'Asian Market Gateway', typeKo: '아시아 시장 관문', dna: 'Market infrastructure · East–West capital', dnaKo: '시장 인프라 · 동서 자본',
    insightKo: '시장 인프라와 동서 자본이 교차합니다. 아시아 컬렉터 프로그램과 갤러리 전속 전략이 맞습니다.',
    signalScores: { market: 89, cultural: 77, opportunity: 83 },
    market: { artists: ['Lee Kit', 'Pak Sheung Chuen'], priceRange: '15K–4.0M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['M+', 'Art Basel HK', 'Para Site'], events: ['Art Basel Hong Kong', 'Hong Kong International Art Fair'], keywords: ['auction market', 'Asian capital', 'East–West'], keywordsKo: ['경매 시장', '아시아 자본', '동서 교차'] },
    industry: ['Finance', 'Hospitality', 'Retail'], industryKo: ['금융', '호스피탈리티', '리테일'],
    opportunity: 'Asian collector programme · gallery representation', opportunityKo: '아시아 컬렉터 프로그램 · 갤러리 전속 전략', opportunityWhy: '경매와 물류가 한곳에 모여 컬렉터 접점을 만들기에 가장 효율적입니다.',
    location: '좁은 산지와 항만 사이에 초고밀도로 쌓아 올린 도시라 공간 비용이 모든 결정을 규정합니다. 자유항 지위와 낮은 관세가 미술품 거래의 물리적 기반을 만들었습니다.',
    heritage: '식민 통치와 반환을 거치며 중국과 서구의 제도가 층층이 남았습니다. M+ 개관으로 지역 현대미술을 스스로 정전화하는 작업이 본격화됐습니다.',
    adaptability: '거래와 물류가 세계에서 가장 빠른 축에 속해 시장 변화를 즉시 흡수합니다. 반면 표현 환경을 둘러싼 제도 변화가 장기 전망의 최대 변수입니다.',
    outlook: '아시아 경매 관문으로서의 기능은 당분간 유지될 것입니다. 싱가포르·서울과의 역할 분담이 앞으로의 위치를 결정합니다.',
    trendNote: '상승 중 한 차례 눌린 뒤 회복합니다. 시장 축은 견조했으나 제도 환경 변화가 다른 축을 끌어내린 구간입니다.',
    trend: [79.0, 80.2, 81.6, 80.8, 82.4, 83.1],
    signatureWork: { title: '1985년 6월–10월', titleOriginal: 'Juin-Octobre 1985', artist: '자오우키', artistOriginal: 'Zao Wou-Ki', year: 1985, priceUsd: '약 6,500만 달러', priceKrw: '약 845억 원', note: '홍콩과 파리를 무대로 활동한 아시아계 작가의 역대 경매 최고가 대형 삼면화', auction: '2018 소더비 홍콩',
      meaning: '세 폭에 걸친 대형 추상으로, 중국 산수의 기운과 서구 추상표현주의의 붓질이 한 화면에서 만납니다.',
      intent: '베이징에서 태어나 파리에 정착한 자오우키는 동서양의 회화 언어를 하나로 합치려는 시도를 평생 이어 갔고, 이 삼면화가 그 정점에 해당합니다.',
      cityLink: '홍콩 경매가 아시아계 작가의 국제 가격을 형성하는 무대임을 증명한 작품입니다. 동서 자본이 교차하는 홍콩 시장의 성격을 그대로 보여 줍니다.',
      image: imgHongKong },
  },
  {
    slug: 'paris', code: 'PAR', name: 'Paris', nameKo: '파리', country: 'France', latitude: 48.8566, longitude: 2.3522,
    index: 87.3, type: 'Historic Market Capital', typeKo: '역사적 시장 수도', dna: 'Institutional prestige · Cultural authority', dnaKo: '기관의 권위 · 문화적 정통성',
    insightKo: '기관의 권위와 문화적 정통성이 자산입니다. 럭셔리 브랜드 아트 프로그램과 기관 협업에 유리합니다.',
    signalScores: { market: 91, cultural: 93, opportunity: 81 },
    market: { artists: ['Pierre Huyghe', 'Sophie Calle'], priceRange: '18K–6.0M+', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Centre Pompidou', 'Palais de Tokyo', 'Fondation Louis Vuitton'], events: ['Paris+ par Art Basel', 'FIAC', 'Paris Art Week'], keywords: ['institutional authority', 'historical canon', 'luxury ecology'], keywordsKo: ['기관의 권위', '역사적 정전', '럭셔리 생태계'] },
    industry: ['Fashion', 'Hospitality', 'Luxury'], industryKo: ['패션', '호스피탈리티', '럭셔리'],
    opportunity: 'Luxury brand art programme · institutional collaboration', opportunityKo: '럭셔리 브랜드 아트 프로그램 · 기관 협업', opportunityWhy: '럭셔리 본사와 대형 기관이 같은 도시에 있어 협업 성사 비용이 낮습니다.',
    location: '센강을 축으로 대형 기관이 도심에 집중되어 보행 거리 안에서 미술사를 통과할 수 있습니다. 유럽 고속철망의 결절점이라 역내 이동이 압도적으로 쉽습니다.',
    heritage: '왕실 컬렉션에서 출발한 공공 미술관 제도의 원형이 만들어진 도시입니다. 19~20세기 아방가르드의 거점이었다는 서사가 지금도 기관 운영의 근거로 작동합니다.',
    adaptability: '제도의 권위가 강한 만큼 검증 절차가 길고, 새 형식의 제도권 진입이 느린 편입니다. 대신 한 번 편입되면 국제적 정당성이 강하게 부여됩니다.',
    outlook: '브렉시트 이후 유럽 미술 시장 기능이 이동하며 거래 축이 강화되고 있습니다. 기관과 럭셔리 산업의 결합이 당분간 성장 동력이 될 전망입니다.',
    trendNote: '안정적으로 우상향합니다. 기관 기반이 워낙 두터워 외부 충격에도 낙폭이 작습니다.',
    trend: [83.5, 84.8, 85.6, 86.2, 86.9, 87.3],
    signatureWork: { title: 'FC1 (화염 회화 1호)', titleOriginal: 'FC1 (Fire-Color 1)', artist: '이브 클라인', artistOriginal: 'Yves Klein', year: 1962, priceUsd: '약 3,650만 달러', priceKrw: '약 420억 원', note: '누보 레알리슴의 기수 · 화염 방사기와 인체 모델을 사용한 실험', auction: '2012 크리스티 뉴욕',
      meaning: '화염방사기로 태운 흔적과 인체의 자국이 겹친 화면으로, 불과 몸처럼 붙잡을 수 없는 것을 그림에 남깁니다.',
      intent: '클라인은 회화를 그리는 일에서 흔적을 남기는 일로 옮겨 놓았습니다. 모델의 몸을 붓처럼 쓰고 마지막을 불로 마무리하는 방식이 그 실험의 결과입니다.',
      cityLink: '파리 누보 레알리슴의 한복판에서 나온 작업입니다. 퐁피두를 비롯한 파리의 기관들이 전후 프랑스 아방가르드를 정전으로 만든 과정과 직결됩니다.',
      image: imgParis },
  },
  {
    slug: 'venice', code: 'VEN', name: 'Venice', nameKo: '베네치아', country: 'Italy', latitude: 45.4408, longitude: 12.3155,
    index: 81.5, type: 'Biennale Prestige Platform', typeKo: '비엔날레 무대 도시', dna: 'Global stage · Curatorial authority', dnaKo: '국제 무대 · 큐레이터십의 권위',
    insightKo: '국제 무대와 큐레이터십의 권위가 중심입니다. 비엔날레 연계 프로그램과 컬렉터 레지던시가 적합합니다.',
    signalScores: { market: 77, cultural: 96, opportunity: 78 },
    market: { artists: ['Emilio Vedova', 'Carlo Scarpa'], priceRange: '10K–2.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Peggy Guggenheim Collection', 'Punta della Dogana', 'La Biennale'], events: ['Venice Biennale', 'Venice Architecture Biennale'], keywords: ['biennale culture', 'national pavilion', 'curatorial prestige'], keywordsKo: ['비엔날레 문화', '국가관', '큐레이터십'] },
    industry: ['Tourism', 'Hospitality', 'Architecture'], industryKo: ['관광', '호스피탈리티', '건축'],
    opportunity: 'Biennale-linked programme · collectors residency', opportunityKo: '비엔날레 연계 프로그램 · 컬렉터 레지던시', opportunityWhy: '2년 주기로 국제 관객이 보장돼 단기 집중형 프로그램의 효율이 높습니다.',
    location: '석호 위 섬이라는 조건 때문에 도시 확장이 불가능하고, 모든 활동이 기존 건물의 전용으로 이뤄집니다. 상주 인구가 적어 도시 기능이 사실상 방문자를 전제로 설계됩니다.',
    heritage: '공화국 시기의 건축과 회화가 도시 전체에 원형에 가깝게 남아 있습니다. 보존 자체가 최대 과제이며, 해수면 상승이 유산의 물리적 존속을 위협합니다.',
    adaptability: '2년 주기 비엔날레가 도시의 시간표를 규정해, 실험은 이 주기에 맞춰 집중됩니다. 상시적 제작 기반은 얇아 행사 밖 기간의 활동이 제한적입니다.',
    outlook: '국제 무대로서의 상징성은 대체하기 어렵습니다. 다만 기후와 관광 과밀이 지속 가능성의 최대 변수로 남습니다.',
    trendNote: '격년 주기의 미세한 등락이 반복됩니다. 비엔날레 개최 연도에 지표가 올라가는 패턴이 그대로 나타납니다.',
    trend: [78.0, 79.2, 80.4, 79.8, 80.9, 81.5],
    signatureWork: { title: '공간 개념, 신의 기대', titleOriginal: 'Concetto Spaziale, La Fine di Dio', artist: '루초 폰타나', artistOriginal: 'Lucio Fontana', year: 1963, priceUsd: '약 3,280만 달러', priceKrw: '약 445억 원', note: '베네치아 비엔날레에서 태동한 공간주의의 알 모양 타공 캔버스 연작', auction: '2024 소더비 뉴욕',
      meaning: '알 모양 캔버스에 구멍을 뚫어, 그림 너머의 실제 공간을 작품 안으로 끌어들인 연작입니다.',
      intent: '폰타나는 「공간주의」를 내세워 2차원 회화의 환영을 끝내려 했습니다. 「신의 종말」이라는 제목은 창조라는 관념 자체를 다시 묻습니다.',
      cityLink: '공간주의가 확산된 무대가 베네치아 비엔날레였습니다. 이탈리아 전후 전위가 국제적 언어가 되는 과정을 상징하는 작품입니다.',
      image: imgVenice },
  },
  {
    slug: 'basel', code: 'BAS', name: 'Basel', nameKo: '바젤', country: 'Switzerland', latitude: 47.5596, longitude: 7.5886,
    index: 85.0, type: 'Fair Capital', typeKo: '아트페어 수도', dna: 'Market infrastructure · Institutional depth', dnaKo: '시장 인프라 · 기관의 두께',
    insightKo: '페어 인프라와 기관의 두께가 동시에 작동합니다. 페어 주간 컬렉터 프로그램과 미술관 파트너십이 핵심입니다.',
    signalScores: { market: 90, cultural: 82, opportunity: 79 },
    market: { artists: ['Peter Fischli', 'Pipilotti Rist'], priceRange: '20K–5.0M+', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Kunstmuseum Basel', 'Art Basel', 'Fondation Beyeler'], events: ['Art Basel', 'Liste Art Fair'], keywords: ['fair infrastructure', 'collector network', 'Swiss precision'], keywordsKo: ['페어 인프라', '컬렉터 네트워크', '스위스식 정밀함'] },
    industry: ['Finance', 'Luxury', 'Hospitality'], industryKo: ['금융', '럭셔리', '호스피탈리티'],
    opportunity: 'Fair-week collector programme · museum partnership', opportunityKo: '페어 주간 컬렉터 프로그램 · 미술관 파트너십', opportunityWhy: '페어 주간에 세계 컬렉터가 한 주간 모여 접점 비용이 가장 낮아집니다.',
    location: '독일·프랑스와 국경이 맞닿은 삼국 접경 도시로, 인구 규모에 비해 국제 접근성이 매우 높습니다. 금융·제약 산업이 만든 자산이 수집 문화의 토대가 됐습니다.',
    heritage: '세계 최초의 시립 미술관으로 꼽히는 쿤스트무제움을 비롯해 공공 컬렉션의 전통이 깊습니다. 도시 규모가 작은 대신 소장품의 밀도가 대단히 높습니다.',
    adaptability: '페어를 중심으로 매년 세계 시장이 한 주간 집결하는 구조가 고착돼 있습니다. 이 구조가 안정적인 만큼 그 밖의 변화는 천천히 일어납니다.',
    outlook: '아트 바젤 브랜드의 확장이 도시 위상을 계속 뒷받침할 전망입니다. 다만 페어 의존도가 높아 개최 구조가 바뀌면 충격이 직접적입니다.',
    trendNote: '높은 수준에서 완만하게 오릅니다. 변동성이 작다는 점 자체가 이 도시 시장 구조의 특징입니다.',
    trend: [81.2, 82.6, 83.4, 84.0, 84.6, 85.0],
    signatureWork: { title: '메타-말레비치', titleOriginal: 'Méta-Malevich', artist: '장 팅겔리', artistOriginal: 'Jean Tinguely', year: 1954, priceUsd: '약 240만 달러', priceKrw: '약 28억 원', note: '바젤 출신 대표 키네틱 아티스트 · 기계 장치와 기하학적 추상의 결합', auction: '2018 크리스티 런던',
      meaning: '말레비치의 기하 추상을 모터로 움직이게 한 부조로, 정지된 절대를 운동으로 뒤집습니다.',
      intent: '팅겔리는 완결된 예술을 거부하고 기계와 소음, 심지어 고장까지 작품에 끌어들여 추상의 경직성을 유쾌하게 조롱했습니다.',
      cityLink: '바젤에서 성장한 작가이며, 팅겔리 미술관과 아트 바젤이 이 도시의 예술 인프라를 이룹니다. 페어와 기관이 함께 작동하는 바젤의 성격과 겹칩니다.',
      image: imgBasel },
  },
  {
    slug: 'tokyo', code: 'TKY', name: 'Tokyo', nameKo: '도쿄', country: 'Japan', latitude: 35.6762, longitude: 139.6503,
    index: 82.0, type: 'Pop-Techno Cultural Force', typeKo: '팝–테크노 문화 강국', dna: 'Material innovation · Cultural export', dnaKo: '소재 혁신 · 문화 수출력',
    insightKo: '소재 혁신과 문화 수출력이 결합합니다. 공예–기술 협업과 팝컬처 브랜드 라이선싱이 기회입니다.',
    signalScores: { market: 80, cultural: 90, opportunity: 80 },
    market: { artists: ['Yayoi Kusama', 'Takashi Murakami'], priceRange: '12K–3.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Mori Art Museum', 'teamLab', '21_21 Design Sight'], events: ['Tokyo Art & Antiques', 'Designart Tokyo'], keywords: ['pop culture', 'material precision', 'techno-craft'], keywordsKo: ['대중문화', '소재의 정밀함', '기술 공예'] },
    industry: ['Fashion', 'Tech', 'Hospitality'], industryKo: ['패션', '테크', '호스피탈리티'],
    opportunity: 'Craft–tech collaboration · pop-culture brand licensing', opportunityKo: '공예–기술 협업 · 팝컬처 브랜드 라이선싱', opportunityWhy: '정밀 제조와 대중문화 IP가 함께 있어 소재 실험과 상품화를 동시에 할 수 있습니다.',
    location: '복수의 부도심이 철도망으로 연결된 다핵 구조라, 문화 시설이 한곳에 집중되지 않고 분산돼 있습니다. 지진 위험이 건축과 전시 설계의 상시 조건으로 작동합니다.',
    heritage: '에도 시기의 공예와 판화 전통이 현대 대중문화로 연속적으로 이어집니다. 고급 미술과 대중 매체의 경계가 다른 도시보다 뚜렷하지 않습니다.',
    adaptability: '새로운 기술과 소재를 제작에 빠르게 결합하는 역량이 뛰어납니다. 반면 미술 시장의 제도적 개방은 제조·기술 부문의 속도를 따라가지 못했습니다.',
    outlook: '팝컬처와 공예 기술을 결합한 수출 모델이 계속 성장할 전망입니다. 세제와 거래 제도가 개선되면 시장 축의 상승 여지가 큽니다.',
    trendNote: '꾸준히 오르되 중간에 한 번 눌립니다. 문화 수출은 늘었지만 국내 거래 제도가 더디게 바뀐 시기가 반영됐습니다.',
    trend: [78.4, 79.6, 80.8, 80.2, 81.4, 82.0],
    signatureWork: { title: '무제 (인피니티 네트)', titleOriginal: 'Untitled', artist: '쿠사마 야요이', artistOriginal: 'Yayoi Kusama', year: 1960, priceUsd: '약 1,050만 달러', priceKrw: '약 130억 원', note: '생존 여성 작가 중 최고 시장성을 보유한 초기 「무한 망」 명작', auction: '2022 필립스 뉴욕',
      meaning: '그물 패턴이 화면 끝까지 반복되며, 자아가 지워지고 무한히 증식하는 감각을 만들어 냅니다.',
      intent: '어린 시절부터 겪은 환각 경험을 그대로 화면에 옮긴 「자기 소멸」의 출발점입니다. 1957년 도미 직후 뉴욕에서 본격적으로 전개했습니다.',
      cityLink: '일본 전후 전위의 실험과 도쿄의 팝·기술 문화가 쿠사마의 국제적 수용을 뒷받침했습니다. 도쿄가 가진 문화 수출력의 전형적인 사례입니다.',
      image: imgTokyo },
  },
  {
    slug: 'shanghai', code: 'SHA', name: 'Shanghai', nameKo: '상하이', country: 'China', latitude: 31.2304, longitude: 121.4737,
    index: 79.6, type: 'Emerging Market Accelerator', typeKo: '신흥 시장 가속 도시', dna: 'Collector growth · Institutional ambition', dnaKo: '컬렉터의 성장 · 기관의 야심',
    insightKo: '컬렉터 층의 성장과 기관의 야심이 맞물립니다. 컬렉터 인게이지먼트와 브랜드 아트 파트너십이 유효합니다.',
    signalScores: { market: 85, cultural: 78, opportunity: 82 },
    market: { artists: ['Liu Wei', 'Zhou Tiehai'], priceRange: '10K–2.0M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Power Station of Art', 'Long Museum', 'Fosun Foundation'], events: ['ART021', 'West Bund Art & Design'], keywords: ['collector class', 'museum building', 'commercial vitality'], keywordsKo: ['컬렉터 계층', '미술관 건립', '상업적 활력'] },
    industry: ['Finance', 'Fashion', 'Tech'], industryKo: ['금융', '패션', '테크'],
    opportunity: 'Collector engagement programme · brand art partnership', opportunityKo: '컬렉터 인게이지먼트 · 브랜드 아트 파트너십', opportunityWhy: '신규 컬렉터가 빠르게 유입돼 초기 관계 형성의 성과가 큽니다.',
    location: '황푸강을 사이에 두고 조계지 건축과 신도심 마천루가 마주 보는 구조입니다. 항만과 금융 기능이 결합해 자본이 문화 시설로 흘러드는 경로가 짧습니다.',
    heritage: '조계지 시기의 국제적 도시 문화가 근대 미술의 토대를 만들었습니다. 그 층이 오래 단절됐다가 1990년대 이후 다시 소환되고 있습니다.',
    adaptability: '민간 미술관이 단기간에 대거 들어설 만큼 자본의 반응 속도가 빠릅니다. 다만 기관의 축적 기간이 짧아 프로그램의 깊이는 아직 검증 중입니다.',
    outlook: '역내 컬렉터 기반의 성장세가 가장 뚜렷한 도시입니다. 민간 미술관의 운영 지속성이 향후 위상을 가를 것입니다.',
    trendNote: '초반부터 꾸준히 가파르게 오릅니다. 컬렉터 계층 형성과 미술관 건립이 같은 시기에 겹친 결과입니다.',
    trend: [72.0, 74.5, 76.8, 77.6, 78.9, 79.6],
    signatureWork: { title: '최후의 만찬', titleOriginal: 'The Last Supper', artist: '쩡판즈', artistOriginal: 'Zeng Fanzhi', year: 1995, priceUsd: '약 2,330만 달러', priceKrw: '약 303억 원', note: '아시아 현대 미술 붐을 이끈 「가면」 연작의 핵심 대작', auction: '2013 소더비 홍콩',
      meaning: '최후의 만찬 구도를 빌려, 붉은 스카프를 맨 가면 쓴 인물들이 수박을 나누는 장면으로 바꿔 놓았습니다.',
      intent: '「가면」 연작은 급속한 도시화 속에서 개인이 쓰게 되는 사회적 가면을 주제로 합니다. 붉은 스카프와 노란 넥타이의 대비가 이념에서 자본으로의 이동을 암시합니다.',
      cityLink: '1990년대 중국의 시장경제 전환과 신흥 컬렉터 계층의 등장을 압축합니다. 상하이가 아시아 현대미술 시장의 가속 장치가 된 시기와 정확히 겹칩니다.',
      image: imgShanghai },
  },
  {
    slug: 'singapore', code: 'SIN', name: 'Singapore', nameKo: '싱가포르', country: 'Singapore', latitude: 1.3521, longitude: 103.8198,
    index: 76.8, type: 'ASEAN Gateway Hub', typeKo: '아세안 관문 허브', dna: 'Regional access · Global finance', dnaKo: '역내 접근성 · 글로벌 금융',
    insightKo: '역내 접근성과 글로벌 금융이 결합합니다. 아세안 컬렉터 프로그램과 다문화 예술 플랫폼이 적합합니다.',
    signalScores: { market: 78, cultural: 73, opportunity: 80 },
    market: { artists: ['Chua Ek Kay', 'Zhuang Guanbin'], priceRange: '8K–1.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['National Gallery Singapore', 'SAM', 'ArtScience Museum'], events: ['Art SG', 'Singapore Art Week'], keywords: ['ASEAN access', 'financial hub', 'multicultural'], keywordsKo: ['아세안 접근성', '금융 허브', '다문화'] },
    industry: ['Finance', 'Tech', 'Hospitality'], industryKo: ['금융', '테크', '호스피탈리티'],
    opportunity: 'ASEAN collector programme · multicultural art platform', opportunityKo: '아세안 컬렉터 프로그램 · 다문화 예술 플랫폼', opportunityWhy: '동남아 전역이 항공 수 시간 거리라 역내 대상 프로그램의 도달 범위가 넓습니다.',
    location: '말라카 해협 입구의 도시국가로, 동남아 전역이 항공 수 시간 거리에 들어옵니다. 국토가 좁아 문화 시설이 국가 계획에 따라 배치됩니다.',
    heritage: '말레이·중국·인도·서구 문화가 겹친 항구 도시의 이력이 그대로 유산이 됩니다. 난양 화파처럼 지역 소재와 서구 기법을 결합한 계보가 정전으로 정리되고 있습니다.',
    adaptability: '정책적으로 문화 인프라를 배치하는 방식이라 방향 전환이 빠릅니다. 상향식 실험보다 계획된 조성이 앞서는 구조입니다.',
    outlook: '아세안 시장의 관문 역할이 강화될 전망입니다. 자생적 작가 생태계를 얼마나 키우느냐가 장기 과제로 남습니다.',
    trendNote: '안정적으로 우상향하며 낙폭이 거의 없습니다. 정책 주도형 투자가 꾸준히 이어진 결과로 읽힙니다.',
    trend: [72.5, 73.8, 75.0, 74.4, 75.9, 76.8],
    signatureWork: { title: '정물화 (두리안이 있는)', titleOriginal: 'Still Life with Big Durian', artist: '조젯 첸', artistOriginal: 'Georgette Chen', year: 1965, priceUsd: '약 170만 달러', priceKrw: '약 22억 원', note: '싱가포르 난양 화파의 선구자 · 동남아 소재와 서양 후기 인상주의의 결합', auction: '2023 크리스티 홍콩',
      meaning: '두리안과 열대 과일을 놓은 정물로, 동남아 고유의 소재를 서양 후기인상주의의 색과 붓질로 다룹니다.',
      intent: '파리와 상하이를 거쳐 싱가포르에 정착한 첸은 지역의 삶을 정물로 기록하며 「난양 화파」의 시각 언어를 만들고자 했습니다.',
      cityLink: '싱가포르 난양 화파의 정체성이 형성되는 지점에 놓인 작품입니다. 내셔널 갤러리 싱가포르가 이 계보를 동남아 미술의 정전으로 세우고 있습니다.',
      image: imgSingapore },
  },
]

export function listCities(): readonly City[] {
  return cities
}

export function findCity(slug: string): City | undefined {
  return cities.find((city) => city.slug === slug)
}

/** Cities A–Z by English name. */
export const citiesByName: readonly City[] = [...cities].sort((a, b) => a.name.localeCompare(b.name))

export function rankCities(): readonly City[] {
  return [...cities].sort((a, b) => b.index - a.index)
}
