import type { City } from '@/types/city'
import imgSeoul from '@/img/Nam-June-Paik-TV-Buddha.jpeg'
import imgBerlin from '@/img/Abstraktes Bild-Gerhard Richter.jpg'
import imgLondon from '@/img/BACON_1969_Three_Studies_of_Lucian_Freud_triptych-620x420.jpg'
import imgNewYork from '@/img/Warhol_Marilyn.jpg'
import imgMexicoCity from '@/img/diego-and-i.jpg'
import imgMelbourne from '@/img/First-Class Marksman.jpg'
import imgAmsterdam from '@/img/Untitled XXV.jpg'
import imgBeijing from '@/img/Twelve_Landscape_Screens_by_Qi_Baishi.jpg'
import imgBarcelona from '@/img/Blue-Star-1-796x1024.jpg'
import imgChicago from '@/img/jimson-weed-white-flower.jpg'
import imgDubai from '@/img/farhad-moshiri-14439_0@2x.jpg'
import imgHongKong from '@/img/Juin-Octobre 1985.jpg'
import imgParis from '@/img/FC1 (Fire-Color 1).jpg'
import imgVenice from '@/img/Concetto Spaziale, La Fine di Dio.jpg'
import imgBasel from '@/img/Méta-Malevich.jpg'
import imgTokyo from '@/img/Yayoi Kusama Untitled.jpg'
import imgShanghai from '@/img/Zeng Fanzhi The Last Supper.jpg'
import imgSingapore from '@/img/Still Life with Big Durian.jpg'

/** Sample years for every city's `trend` array — one year per value. */
export const TREND_YEARS = [2000, 2005, 2010, 2015, 2020, 2025] as const

export const cities: readonly City[] = [
  {
    slug: 'seoul', code: 'SEO', name: 'Seoul', nameKo: '서울', country: 'South Korea', latitude: 37.5665, longitude: 126.978,
    index: 78.4, type: 'Networked Experimenter', typeKo: '네트워크형 실험 도시', dna: 'Fast systems · Fluid formats',
    insightKo: '빠른 실행 체계와 유연한 형식 실험이 강점입니다. 인터랙티브 오브제 쇼룸과 작가 에디션 상품으로 연결할 수 있습니다.',
    signalScores: { market: 78, cultural: 87, opportunity: 82 },
    market: { artists: ['Lee Bul', 'Haegue Yang'], priceRange: '10K–1.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['MMCA', 'Leeum', 'Seoul Museum of Art'], events: ['Seoul Mediacity Biennale', 'Frieze Seoul'], keywords: ['digital material', 'institutional scale', 'Asian bridge'] },
    industry: ['Furniture', 'Hotel', 'Fashion'], opportunity: 'Interactive object showroom · artist-edition product',
    trend: [71.2, 73.6, 75.0, 74.1, 76.8, 78.4],
    signatureWork: { title: 'TV 부처', titleOriginal: 'TV Buddha', artist: '백남준', artistOriginal: 'Nam June Paik', year: 1974, note: '18세기 목조 불상과 폐쇄회로 TV가 서로를 마주 보는 비디오 설치 · 백남준의 대표 아이콘', collection: '스테델릭 미술관, 암스테르담', collectionNote: '1974년 원본 · 이후 여러 변주작 제작', commission: '1974 갈레리아 보니노, 뉴욕 초연',
      meaning: '거울보다 왜곡이 적은 카메라와 TV 화면을 통해 불상은 자신을 영원히 응시합니다. 끝없는 자기 응시와 자기 반성이라는 깨달은 자의 속성을 매체의 구조로 옮겨 놓은 것입니다. 동시에 전원을 끊는 순간 꺼져 버리는 TV 화면은 인간 의식의 속성에 대한 비유이기도 합니다.',
      intent: '백남준은 동양의 관조와 서구의 기술을 한자리에 놓고, TV가 수신 장치가 아니라 사유의 도구가 될 수 있는지 물었습니다. 실시간 영상은 편집도 지연도 없이 오직 지금만을 비춥니다.',
      cityLink: '서울에서 태어난 백남준이 동아시아의 불교 도상과 서구 미디어 기술을 하나로 묶은 작업입니다. 전통적 형식과 새 매체를 빠르게 접붙이는 서울의 실험 방식과 그대로 겹칩니다.',
      image: imgSeoul },
  },
  {
    slug: 'berlin', code: 'BER', name: 'Berlin', nameKo: '베를린', country: 'Germany', latitude: 52.52, longitude: 13.405,
    index: 80.2, type: 'Independent Production Lab', typeKo: '독립 제작 실험실', dna: 'Dense production · Open networks',
    insightKo: '밀도 높은 제작 기반과 열린 네트워크가 축입니다. 순환 소재 레지던시와 커뮤니티 쇼룸이 유효합니다.',
    signalScores: { market: 62, cultural: 91, opportunity: 79 },
    market: { artists: ['Olafur Eliasson', 'Katharina Grosse'], priceRange: '8K–2.0M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Hamburger Bahnhof', 'KW', 'Gropius Bau'], events: ['Berlin Art Week', 'Gallery Weekend'], keywords: ['independent space', 'critical practice', 'reuse'] },
    industry: ['Fashion', 'Furniture', 'Urban space'], opportunity: 'Circular-material residency · community showroom',
    trend: [76.5, 78.0, 77.2, 79.4, 79.0, 80.2],
    signatureWork: { title: '추상화', titleOriginal: 'Abstraktes Bild', artist: '게르하르트 리히터', artistOriginal: 'Gerhard Richter', year: 1986, priceUsd: '약 4,630만 달러', priceKrw: '약 510억 원', note: '스퀴지 기법으로 완성된 독일 현대 미술 거장의 대작', auction: '2015 소더비 런던',
      meaning: '스퀴지로 물감층을 밀어내 우연과 통제가 뒤섞인 화면으로, 회화가 무엇을 재현할 수 있는가를 되묻습니다.',
      intent: '사진적 사실주의와 추상을 평생 오가며 이미지의 신뢰성을 의심해 온 작가가, 붓 대신 스퀴지를 써서 결정권의 상당 부분을 우연에 넘긴 결과물입니다.',
      cityLink: '전후 독일 미술이 역사와 이미지를 다루는 방식을 대표합니다. 비판적 실천과 독립 제작 기반이 두터운 베를린 씬이 이 계보를 현재형으로 잇고 있습니다.',
      image: imgBerlin },
  },
  {
    slug: 'london', code: 'LON', name: 'London', nameKo: '런던', country: 'United Kingdom', latitude: 51.5072, longitude: -0.1276,
    index: 88.6, type: 'Global Market Institution', typeKo: '글로벌 시장·기관 중심지', dna: 'Market depth · Institutional reach',
    insightKo: '시장의 깊이와 기관의 영향력이 함께 작동합니다. 컬처 컨시어지와 컬렉션 기반 브랜드 프로그램에 적합합니다.',
    signalScores: { market: 93, cultural: 88, opportunity: 80 },
    market: { artists: ['Lubaina Himid', 'Damien Hirst'], priceRange: '20K–5.0M+', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Tate Modern', 'Serpentine', 'ICA'], events: ['Frieze London', 'London Gallery Weekend'], keywords: ['global market', 'public institution', 'diaspora'] },
    industry: ['Finance', 'Hospitality', 'Fashion'], opportunity: 'Cultural concierge · collection-led brand programme',
    trend: [84.0, 85.6, 86.9, 86.2, 87.8, 88.6],
    signatureWork: { title: '루시안 프로이트의 세 가지 습작', titleOriginal: 'Three Studies of Lucian Freud', artist: '프랜시스 베이컨', artistOriginal: 'Francis Bacon', year: 1969, priceUsd: '약 1억 4,240만 달러', priceKrw: '약 1,520억 원', note: '런던 스쿨의 정점이자 삼면화 구성의 기념비적 작품', auction: '2013 크리스티 뉴욕',
      meaning: '친구이자 경쟁자였던 화가 루시안 프로이트를 세 각도에서 포착한 삼면화로, 인간 신체의 취약함과 심리적 압박을 드러냅니다.',
      intent: '베이컨은 가까운 인물을 반복해 그렸고 프로이트와의 우정과 경쟁이 핵심 소재였습니다. 제단화의 삼면 구조를 세속의 초상으로 옮겨 놓았습니다.',
      cityLink: '전후 런던 소호를 거점으로 한 「런던 스쿨」의 상징입니다. 런던이 기관과 시장 양쪽에서 현대미술의 가격과 정전을 동시에 만들어 온 도시임을 보여 줍니다.',
      image: imgLondon },
  },
  {
    slug: 'new-york', code: 'NYC', name: 'New York', nameKo: '뉴욕', country: 'United States', latitude: 40.7128, longitude: -74.006,
    index: 91.4, type: 'Global Market Engine', typeKo: '글로벌 시장 엔진', dna: 'Capital concentration · Network power',
    insightKo: '자본 집중도와 네트워크 영향력이 최상위입니다. 컬렉션 인텔리전스 서비스와 문화 플래그십에 유리합니다.',
    signalScores: { market: 97, cultural: 91, opportunity: 86 },
    market: { artists: ['Julie Mehretu', 'Jean-Michel Basquiat'], priceRange: '25K–10M+', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['MoMA', 'Whitney', 'New Museum'], events: ['The Armory Show', 'Frieze New York'], keywords: ['market liquidity', 'gallery network', 'global influence'] },
    industry: ['Finance', 'Retail', 'Media'], opportunity: 'Collection intelligence service · cultural flagship',
    trend: [87.0, 88.4, 89.6, 90.1, 90.8, 91.4],
    signatureWork: { title: '샷 세이지 블루 메릴린', titleOriginal: 'Shot Sage Blue Marilyn', artist: '앤디 워홀', artistOriginal: 'Andy Warhol', year: 1964, priceUsd: '약 1억 9,504만 달러', priceKrw: '약 2,500억 원', note: '20세기 미술품 경매 사상 최고가이자 미국 작가 역대 최고 기록', auction: '2022 크리스티 뉴욕',
      meaning: '마릴린 먼로의 홍보 사진을 실크스크린으로 반복해, 대중매체가 만든 이미지와 명성의 덧없음을 함께 드러냅니다.',
      intent: '워홀은 대량 복제 이미지를 미술로 끌어들여 원본성 개념을 해체했습니다. 「샷」이라는 제목은 1964년 팩토리에서 한 방문객이 작품 더미에 총을 쏜 사건에서 유래했습니다.',
      cityLink: '팩토리를 중심으로 한 뉴욕의 상업·미디어 문화가 그대로 재료가 된 작품입니다. 뉴욕이 가진 자본 집중도와 시장 규모를 가장 압축적으로 보여 줍니다.',
      image: imgNewYork },
  },
  {
    slug: 'mexico-city', code: 'MEX', name: 'Mexico City', nameKo: '멕시코시티', country: 'Mexico', latitude: 19.4326, longitude: -99.1332,
    index: 72.1, type: 'Local–Global Generator', typeKo: '로컬–글로벌 생성 도시', dna: 'Material culture · Independent energy',
    insightKo: '재료 문화와 독립적 에너지가 원동력입니다. 메이커 중심 호스피탈리티와 소재 리서치 컬렉션이 어울립니다.',
    signalScores: { market: 68, cultural: 84, opportunity: 77 },
    market: { artists: ['Gabriel Orozco', 'Minerva Cuevas'], priceRange: '5K–900K', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Museo Jumex', 'MUAC', 'Kurimanzutto'], events: ['Zona Maco', 'Material Art Fair'], keywords: ['local material', 'artist-run', 'public life'] },
    industry: ['Food', 'Tourism', 'Furniture'], opportunity: 'Maker-led hospitality · material research collection',
    trend: [65.4, 67.8, 69.0, 68.2, 70.6, 72.1],
    signatureWork: { title: '디에고와 나', titleOriginal: 'Diego y yo', artist: '프리다 칼로', artistOriginal: 'Frida Kahlo', year: 1949, priceUsd: '약 3,490만 달러', priceKrw: '약 412억 원', note: '라틴아메리카 미술 사상 최고 경매가를 기록한 자화상', auction: '2021 소더비 뉴욕',
      meaning: '이마에 남편 디에고 리베라의 얼굴이 떠 있고 눈물을 흘리는 자화상으로, 사랑과 고통이 분리되지 않는 상태를 그립니다.',
      intent: '리베라와 배우 마리아 펠릭스의 관계로 괴로워하던 시기에 그렸습니다. 신체적 고통과 결혼 생활은 칼로가 평생 자기 몸을 통해 기록한 주제였습니다.',
      cityLink: '코요아칸의 카사 아술을 중심으로 한 멕시코시티 예술가 공동체에서 태어난 작업입니다. 멕시코 정체성 운동과 라틴아메리카 미술의 국제적 재평가를 함께 상징합니다.',
      image: imgMexicoCity },
  },
  {
    slug: 'melbourne', code: 'MEL', name: 'Melbourne', nameKo: '멜버른', country: 'Australia', latitude: -37.8136, longitude: 144.9631,
    index: 74.8, type: 'Participation Hub', typeKo: '시민 참여 허브', dna: 'Civic access · Distributed culture',
    insightKo: '공공 접근성과 분산된 문화 기반이 특징입니다. 동네 단위 아트 루트와 참여형 호텔 프로그램이 맞습니다.',
    signalScores: { market: 66, cultural: 86, opportunity: 74 },
    market: { artists: ['Patricia Piccinini', 'Brook Andrew'], priceRange: '6K–700K', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['NGV', 'ACCA', 'ACMI'], events: ['Melbourne Art Fair', 'RISING'], keywords: ['public participation', 'moving image', 'First Nations'] },
    industry: ['Tourism', 'Education', 'Hospitality'], opportunity: 'Neighbourhood art route · participatory hotel programme',
    trend: [70.0, 71.5, 73.0, 72.4, 74.0, 74.8],
    signatureWork: { title: '퍼스트 클래스 마크스맨', titleOriginal: 'First-Class Marksman', artist: '시드니 놀란', artistOriginal: 'Sidney Nolan', year: 1946, priceUsd: '약 390만 달러', priceKrw: '약 51억 원', note: '호주 현대 미술 아이콘 「네드 켈리」 연작 중 개인 소장 핵심작', auction: '2010 멘지스 경매',
      meaning: '검은 사각 투구를 쓴 무법자 네드 켈리가 황량한 호주 풍경 속에 서 있는 장면으로, 식민지 신화를 다시 쓴 연작의 핵심작입니다.',
      intent: '놀란은 켈리를 영웅도 악당도 아닌 양가적 인물로 그려, 호주라는 국가의 자기 서사를 회화로 재구성하려 했습니다.',
      cityLink: '멜버른 하이데에서 제작되었고 빅토리아주가 켈리 이야기의 실제 무대입니다. NGV를 비롯한 멜버른 기관이 호주 미술의 정전을 세우는 과정과 맞물립니다.',
      image: imgMelbourne },
  },
  {
    slug: 'amsterdam', code: 'AMS', name: 'Amsterdam', nameKo: '암스테르담', country: 'Netherlands', latitude: 52.3676, longitude: 4.9041,
    index: 76.3, type: 'Critical Discourse Hub', typeKo: '비평 담론 허브', dna: 'Institutional critique · Public access',
    insightKo: '기관 비평과 공공 접근성이 중심축입니다. 디자인 리서치 레지던시와 시민 예술 프로그램이 적합합니다.',
    signalScores: { market: 72, cultural: 84, opportunity: 76 },
    market: { artists: ['Rineke Dijkstra', 'Marlene Dumas'], priceRange: '8K–1.8M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Stedelijk Museum', 'EYE Filmmuseum', 'Foam'], events: ['Art Amsterdam', 'UNSEEN'], keywords: ['critical theory', 'photography', 'civic institution'] },
    industry: ['Tech', 'Fashion', 'Hospitality'], opportunity: 'Design-research residency · civic art programme',
    trend: [73.0, 74.2, 75.6, 74.8, 75.9, 76.3],
    signatureWork: { title: '무제 XXV', titleOriginal: 'Untitled XXV', artist: '빌럼 데 쿠닝', artistOriginal: 'Willem de Kooning', year: 1977, priceUsd: '약 6,630만 달러', priceKrw: '약 770억 원', note: '뉴욕 추상표현주의를 이끈 네덜란드 출신 거장의 후기 대형 추상화', auction: '2016 크리스티 뉴욕',
      meaning: '격렬한 붓질이 풍경과 신체 사이를 오가는 후기 추상으로, 물감 자체의 물질성과 속도가 화면을 지배합니다.',
      intent: '네덜란드에서 미국으로 건너가 추상표현주의를 이끈 작가가, 1970년대 롱아일랜드 이주 이후 빛과 물의 감각을 화면에 끌어들인 시기의 작업입니다.',
      cityLink: '로테르담에서 받은 네덜란드식 미술 교육이 기법의 토대가 되었고, 암스테르담 스테델릭 미술관이 그를 유럽에 소개하며 네덜란드 현대미술의 국제적 좌표를 만들었습니다.',
      image: imgAmsterdam },
  },
  {
    slug: 'beijing', code: 'BEI', name: 'Beijing', nameKo: '베이징', country: 'China', latitude: 39.9042, longitude: 116.4074,
    index: 77.9, type: 'State-Institutional Force', typeKo: '국가·기관 주도 도시', dna: 'Scale infrastructure · Cultural power',
    insightKo: '대규모 인프라와 문화적 영향력이 결합합니다. 기관 파트너십과 동서 문화 교량 역할이 기회입니다.',
    signalScores: { market: 81, cultural: 80, opportunity: 75 },
    market: { artists: ['Ai Weiwei', 'Zhang Huan'], priceRange: '12K–2.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['CAFA Art Museum', '798 Art District', 'UCCA'], events: ['Beijing 798 Art Festival', 'Art Beijing'], keywords: ['state support', 'contemporary scale', 'Eastern canon'] },
    industry: ['Tech', 'Fashion', 'Architecture'], opportunity: 'Institutional partnership · East–West cultural bridge',
    trend: [74.5, 76.0, 75.2, 77.0, 76.8, 77.9],
    signatureWork: { title: '산수십이조병', titleOriginal: 'Twelve Landscape Screens', artist: '치바이스', artistOriginal: 'Qi Baishi', year: 1925, priceUsd: '약 1억 4,080만 달러', priceKrw: '약 1,933억 원', note: '중국 미술품 사상 최초로 1억 달러를 돌파한 12폭 병풍 수묵화', auction: '2017 폴리옥션 베이징',
      meaning: '열두 폭 병풍에 펼친 산수로, 문인화의 형식을 지키면서도 일상의 풍경과 생명력을 끌어들였습니다.',
      intent: '목수 출신으로 독학한 치바이스는 예순 이후 화풍을 스스로 바꾸는 「쇠년변법」을 감행해, 전통을 따르되 자신의 눈으로 다시 보는 길을 택했습니다.',
      cityLink: '베이징에 정착해 활동하며 중국 근대 회화의 중심이 되었습니다. 국가와 기관이 주도하는 베이징 미술 체계에서 정전의 자리를 차지한 작가입니다.',
      image: imgBeijing },
  },
  {
    slug: 'barcelona', code: 'BCN', name: 'Barcelona', nameKo: '바르셀로나', country: 'Spain', latitude: 41.3851, longitude: 2.1734,
    index: 73.5, type: 'Mediterranean Creative Node', typeKo: '지중해 창작 거점', dna: 'Architecture culture · Grassroots energy',
    insightKo: '건축 문화와 풀뿌리 에너지가 공존합니다. 건축–예술 투어와 비디오 아트 베뉴 프로그램이 유효합니다.',
    signalScores: { market: 69, cultural: 82, opportunity: 76 },
    market: { artists: ['Joan Miró', 'Antoni Tàpies'], priceRange: '6K–1.2M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['MACBA', 'Fundació Joan Miró', 'CCCB'], events: ['Art Barcelona', 'Loop Festival'], keywords: ['architecture culture', 'video art', 'grassroots'] },
    industry: ['Tourism', 'Fashion', 'Hospitality'], opportunity: 'Architecture-art tour · video art venue programme',
    trend: [69.8, 71.0, 72.4, 71.6, 72.9, 73.5],
    signatureWork: { title: '회화 (에투알 블뢰)', titleOriginal: 'Peinture (Étoile Bleue)', artist: '호안 미로', artistOriginal: 'Joan Miró', year: 1927, priceUsd: '약 3,690만 달러', priceKrw: '약 420억 원', note: '카탈루냐 초현실주의 거장의 「꿈의 회화」 시기 결정적 작업', auction: '2012 소더비 런던',
      meaning: '붉은 바탕 위에 푸른 별이 떠 있는 「꿈의 회화」로, 형상을 기호로 환원해 시적인 우주를 만듭니다.',
      intent: '파리 초현실주의 그룹과 교류하며 무의식과 자동기술을 회화의 방법으로 삼았습니다. 재현을 버리고 기호와 여백만으로 화면을 구성하려 했습니다.',
      cityLink: '바르셀로나에서 태어난 작가에게 카탈루냐의 풍토와 언어는 평생의 뿌리였습니다. 몬주익의 호안 미로 재단은 지금도 도시 문화 인프라의 한 축입니다.',
      image: imgBarcelona },
  },
  {
    slug: 'chicago', code: 'CHI', name: 'Chicago', nameKo: '시카고', country: 'United States', latitude: 41.8781, longitude: -87.6298,
    index: 75.2, type: 'Civic Collection Leader', typeKo: '시민 컬렉션 선도 도시', dna: 'Public access · Collection depth',
    insightKo: '공공 접근성과 소장품의 깊이가 강점입니다. 시민 예술 프로그램과 건축 중심 경험 설계에 적합합니다.',
    signalScores: { market: 74, cultural: 83, opportunity: 72 },
    market: { artists: ['Kerry James Marshall', 'Chris Ware'], priceRange: '10K–2.0M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Art Institute of Chicago', 'MCA Chicago', 'DuSable'], events: ['EXPO Chicago', 'Chicago Architecture Biennial'], keywords: ['civic collection', 'architecture', 'Black artists'] },
    industry: ['Finance', 'Architecture', 'Education'], opportunity: 'Civic art programme · architecture-led experience',
    trend: [72.0, 73.4, 72.8, 74.1, 74.6, 75.2],
    signatureWork: { title: '흰 독말풀 / 백색 꽃 1호', titleOriginal: 'Jimson Weed/White Flower No. 1', artist: '조지아 오키프', artistOriginal: 'Georgia O’Keeffe', year: 1932, priceUsd: '약 4,440만 달러', priceKrw: '약 480억 원', note: 'SAIC 출신 거장 · 전 세계 여성 작가 경매 사상 최고가 기록', auction: '2014 소더비 뉴욕',
      meaning: '독말풀 꽃을 화면 가득 확대해, 스쳐 지나가던 대상을 정면으로 마주 보게 만드는 작품입니다.',
      intent: '아무도 꽃을 제대로 보지 않는다고 여긴 오키프는, 크게 그려서라도 보게 만들겠다는 생각으로 확대 구도를 밀고 나갔습니다.',
      cityLink: '시카고 미술관 부설 학교에서 수학하며 화가의 길을 시작했습니다. 시민 컬렉션과 미술 교육이 두터운 시카고의 기반이 그의 출발점이었습니다.',
      image: imgChicago },
  },
  {
    slug: 'dubai', code: 'DXB', name: 'Dubai', nameKo: '두바이', country: 'UAE', latitude: 25.2048, longitude: 55.2708,
    index: 71.8, type: 'Global Connector Hub', typeKo: '글로벌 연결 허브', dna: 'Capital mobility · East–West bridge',
    insightKo: '자본의 이동성과 동서 교량 역할이 핵심입니다. 고액자산가 아트 어드바이저리와 문화 관광 프로그램이 유망합니다.',
    signalScores: { market: 76, cultural: 65, opportunity: 81 },
    market: { artists: ['Etel Adnan', 'Hassan Sharif'], priceRange: '8K–1.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Alserkal Avenue', 'Louvre Abu Dhabi', 'Jameel Arts Centre'], events: ['Art Dubai', 'Dubai Design Week'], keywords: ['free zone culture', 'Middle East bridge', 'ultra-HNW'] },
    industry: ['Hospitality', 'Finance', 'Retail'], opportunity: 'HNW art advisory · cultural tourism programme',
    trend: [63.0, 66.4, 68.2, 69.5, 70.8, 71.8],
    signatureWork: { title: '에스크 (사랑)', titleOriginal: 'Eshgh (Love)', artist: '파르하드 모시리', artistOriginal: 'Farhad Moshiri', year: 2007, priceUsd: '약 104만 달러', priceKrw: '약 12억 원', note: '중동 현대 미술품 최초로 100만 달러를 돌파한 크리스털 레터링 작업', auction: '2008 보넘스 두바이',
      meaning: '스와로브스키 크리스털로 쓴 페르시아어 「사랑」으로, 장식과 소비문화를 전통 서예의 형식 위에 겹쳐 놓았습니다.',
      intent: '모시리는 이란의 대중문화와 고급 장식 전통을 동시에 인용해, 중동 현대미술이 놓인 상업적 조건 자체를 작품의 재료로 삼았습니다.',
      cityLink: '두바이 경매에서 중동 현대미술 최초로 100만 달러를 넘겼습니다. 두바이가 역내 미술시장 허브로 올라선 전환점을 표시하는 작품입니다.',
      image: imgDubai },
  },
  {
    slug: 'hong-kong', code: 'HKG', name: 'Hong Kong', nameKo: '홍콩', country: 'China SAR', latitude: 22.3193, longitude: 114.1694,
    index: 83.1, type: 'Asian Market Gateway', typeKo: '아시아 시장 관문', dna: 'Market infrastructure · East–West capital',
    insightKo: '시장 인프라와 동서 자본이 교차합니다. 아시아 컬렉터 프로그램과 갤러리 전속 전략이 맞습니다.',
    signalScores: { market: 89, cultural: 77, opportunity: 83 },
    market: { artists: ['Lee Kit', 'Pak Sheung Chuen'], priceRange: '15K–4.0M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['M+', 'Art Basel HK', 'Para Site'], events: ['Art Basel Hong Kong', 'Hong Kong International Art Fair'], keywords: ['auction market', 'Asian capital', 'East–West'] },
    industry: ['Finance', 'Hospitality', 'Retail'], opportunity: 'Asian collector programme · gallery representation',
    trend: [79.0, 80.2, 81.6, 80.8, 82.4, 83.1],
    signatureWork: { title: '1985년 6월–10월', titleOriginal: 'Juin-Octobre 1985', artist: '자오우키', artistOriginal: 'Zao Wou-Ki', year: 1985, priceUsd: '약 6,500만 달러', priceKrw: '약 845억 원', note: '홍콩과 파리를 무대로 활동한 아시아계 작가의 역대 경매 최고가 대형 삼면화', auction: '2018 소더비 홍콩',
      meaning: '세 폭에 걸친 대형 추상으로, 중국 산수의 기운과 서구 추상표현주의의 붓질이 한 화면에서 만납니다.',
      intent: '베이징에서 태어나 파리에 정착한 자오우키는 동서양의 회화 언어를 하나로 합치려는 시도를 평생 이어 갔고, 이 삼면화가 그 정점에 해당합니다.',
      cityLink: '홍콩 경매가 아시아계 작가의 국제 가격을 형성하는 무대임을 증명한 작품입니다. 동서 자본이 교차하는 홍콩 시장의 성격을 그대로 보여 줍니다.',
      image: imgHongKong },
  },
  {
    slug: 'paris', code: 'PAR', name: 'Paris', nameKo: '파리', country: 'France', latitude: 48.8566, longitude: 2.3522,
    index: 87.3, type: 'Historic Market Capital', typeKo: '역사적 시장 수도', dna: 'Institutional prestige · Cultural authority',
    insightKo: '기관의 권위와 문화적 정통성이 자산입니다. 럭셔리 브랜드 아트 프로그램과 기관 협업에 유리합니다.',
    signalScores: { market: 91, cultural: 93, opportunity: 81 },
    market: { artists: ['Pierre Huyghe', 'Sophie Calle'], priceRange: '18K–6.0M+', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Centre Pompidou', 'Palais de Tokyo', 'Fondation Louis Vuitton'], events: ['Paris+ par Art Basel', 'FIAC', 'Paris Art Week'], keywords: ['institutional authority', 'historical canon', 'luxury ecology'] },
    industry: ['Fashion', 'Hospitality', 'Luxury'], opportunity: 'Luxury brand art programme · institutional collaboration',
    trend: [83.5, 84.8, 85.6, 86.2, 86.9, 87.3],
    signatureWork: { title: 'FC1 (화염 회화 1호)', titleOriginal: 'FC1 (Fire-Color 1)', artist: '이브 클라인', artistOriginal: 'Yves Klein', year: 1962, priceUsd: '약 3,650만 달러', priceKrw: '약 420억 원', note: '누보 레알리슴의 기수 · 화염 방사기와 인체 모델을 사용한 실험', auction: '2012 크리스티 뉴욕',
      meaning: '화염방사기로 태운 흔적과 인체의 자국이 겹친 화면으로, 불과 몸처럼 붙잡을 수 없는 것을 그림에 남깁니다.',
      intent: '클라인은 회화를 그리는 일에서 흔적을 남기는 일로 옮겨 놓았습니다. 모델의 몸을 붓처럼 쓰고 마지막을 불로 마무리하는 방식이 그 실험의 결과입니다.',
      cityLink: '파리 누보 레알리슴의 한복판에서 나온 작업입니다. 퐁피두를 비롯한 파리의 기관들이 전후 프랑스 아방가르드를 정전으로 만든 과정과 직결됩니다.',
      image: imgParis },
  },
  {
    slug: 'venice', code: 'VEN', name: 'Venice', nameKo: '베네치아', country: 'Italy', latitude: 45.4408, longitude: 12.3155,
    index: 81.5, type: 'Biennale Prestige Platform', typeKo: '비엔날레 무대 도시', dna: 'Global stage · Curatorial authority',
    insightKo: '국제 무대와 큐레이터십의 권위가 중심입니다. 비엔날레 연계 프로그램과 컬렉터 레지던시가 적합합니다.',
    signalScores: { market: 77, cultural: 96, opportunity: 78 },
    market: { artists: ['Emilio Vedova', 'Carlo Scarpa'], priceRange: '10K–2.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Peggy Guggenheim Collection', 'Punta della Dogana', 'La Biennale'], events: ['Venice Biennale', 'Venice Architecture Biennale'], keywords: ['biennale culture', 'national pavilion', 'curatorial prestige'] },
    industry: ['Tourism', 'Hospitality', 'Architecture'], opportunity: 'Biennale-linked programme · collectors residency',
    trend: [78.0, 79.2, 80.4, 79.8, 80.9, 81.5],
    signatureWork: { title: '공간 개념, 신의 기대', titleOriginal: 'Concetto Spaziale, La Fine di Dio', artist: '루초 폰타나', artistOriginal: 'Lucio Fontana', year: 1963, priceUsd: '약 3,280만 달러', priceKrw: '약 445억 원', note: '베네치아 비엔날레에서 태동한 공간주의의 알 모양 타공 캔버스 연작', auction: '2024 소더비 뉴욕',
      meaning: '알 모양 캔버스에 구멍을 뚫어, 그림 너머의 실제 공간을 작품 안으로 끌어들인 연작입니다.',
      intent: '폰타나는 「공간주의」를 내세워 2차원 회화의 환영을 끝내려 했습니다. 「신의 종말」이라는 제목은 창조라는 관념 자체를 다시 묻습니다.',
      cityLink: '공간주의가 확산된 무대가 베네치아 비엔날레였습니다. 이탈리아 전후 전위가 국제적 언어가 되는 과정을 상징하는 작품입니다.',
      image: imgVenice },
  },
  {
    slug: 'basel', code: 'BAS', name: 'Basel', nameKo: '바젤', country: 'Switzerland', latitude: 47.5596, longitude: 7.5886,
    index: 85.0, type: 'Fair Capital', typeKo: '아트페어 수도', dna: 'Market infrastructure · Institutional depth',
    insightKo: '페어 인프라와 기관의 두께가 동시에 작동합니다. 페어 주간 컬렉터 프로그램과 미술관 파트너십이 핵심입니다.',
    signalScores: { market: 90, cultural: 82, opportunity: 79 },
    market: { artists: ['Peter Fischli', 'Pipilotti Rist'], priceRange: '20K–5.0M+', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Kunstmuseum Basel', 'Art Basel', 'Fondation Beyeler'], events: ['Art Basel', 'Liste Art Fair'], keywords: ['fair infrastructure', 'collector network', 'Swiss precision'] },
    industry: ['Finance', 'Luxury', 'Hospitality'], opportunity: 'Fair-week collector programme · museum partnership',
    trend: [81.2, 82.6, 83.4, 84.0, 84.6, 85.0],
    signatureWork: { title: '메타-말레비치', titleOriginal: 'Méta-Malevich', artist: '장 팅겔리', artistOriginal: 'Jean Tinguely', year: 1954, priceUsd: '약 240만 달러', priceKrw: '약 28억 원', note: '바젤 출신 대표 키네틱 아티스트 · 기계 장치와 기하학적 추상의 결합', auction: '2018 크리스티 런던',
      meaning: '말레비치의 기하 추상을 모터로 움직이게 한 부조로, 정지된 절대를 운동으로 뒤집습니다.',
      intent: '팅겔리는 완결된 예술을 거부하고 기계와 소음, 심지어 고장까지 작품에 끌어들여 추상의 경직성을 유쾌하게 조롱했습니다.',
      cityLink: '바젤에서 성장한 작가이며, 팅겔리 미술관과 아트 바젤이 이 도시의 예술 인프라를 이룹니다. 페어와 기관이 함께 작동하는 바젤의 성격과 겹칩니다.',
      image: imgBasel },
  },
  {
    slug: 'tokyo', code: 'TKY', name: 'Tokyo', nameKo: '도쿄', country: 'Japan', latitude: 35.6762, longitude: 139.6503,
    index: 82.0, type: 'Pop-Techno Cultural Force', typeKo: '팝–테크노 문화 강국', dna: 'Material innovation · Cultural export',
    insightKo: '소재 혁신과 문화 수출력이 결합합니다. 공예–기술 협업과 팝컬처 브랜드 라이선싱이 기회입니다.',
    signalScores: { market: 80, cultural: 90, opportunity: 80 },
    market: { artists: ['Yayoi Kusama', 'Takashi Murakami'], priceRange: '12K–3.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Mori Art Museum', 'teamLab', '21_21 Design Sight'], events: ['Tokyo Art & Antiques', 'Designart Tokyo'], keywords: ['pop culture', 'material precision', 'techno-craft'] },
    industry: ['Fashion', 'Tech', 'Hospitality'], opportunity: 'Craft–tech collaboration · pop-culture brand licensing',
    trend: [78.4, 79.6, 80.8, 80.2, 81.4, 82.0],
    signatureWork: { title: '무제 (인피니티 네트)', titleOriginal: 'Untitled', artist: '쿠사마 야요이', artistOriginal: 'Yayoi Kusama', year: 1960, priceUsd: '약 1,050만 달러', priceKrw: '약 130억 원', note: '생존 여성 작가 중 최고 시장성을 보유한 초기 「무한 망」 명작', auction: '2022 필립스 뉴욕',
      meaning: '그물 패턴이 화면 끝까지 반복되며, 자아가 지워지고 무한히 증식하는 감각을 만들어 냅니다.',
      intent: '어린 시절부터 겪은 환각 경험을 그대로 화면에 옮긴 「자기 소멸」의 출발점입니다. 1957년 도미 직후 뉴욕에서 본격적으로 전개했습니다.',
      cityLink: '일본 전후 전위의 실험과 도쿄의 팝·기술 문화가 쿠사마의 국제적 수용을 뒷받침했습니다. 도쿄가 가진 문화 수출력의 전형적인 사례입니다.',
      image: imgTokyo },
  },
  {
    slug: 'shanghai', code: 'SHA', name: 'Shanghai', nameKo: '상하이', country: 'China', latitude: 31.2304, longitude: 121.4737,
    index: 79.6, type: 'Emerging Market Accelerator', typeKo: '신흥 시장 가속 도시', dna: 'Collector growth · Institutional ambition',
    insightKo: '컬렉터 층의 성장과 기관의 야심이 맞물립니다. 컬렉터 인게이지먼트와 브랜드 아트 파트너십이 유효합니다.',
    signalScores: { market: 85, cultural: 78, opportunity: 82 },
    market: { artists: ['Liu Wei', 'Zhou Tiehai'], priceRange: '10K–2.0M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['Power Station of Art', 'Long Museum', 'Fosun Foundation'], events: ['ART021', 'West Bund Art & Design'], keywords: ['collector class', 'museum building', 'commercial vitality'] },
    industry: ['Finance', 'Fashion', 'Tech'], opportunity: 'Collector engagement programme · brand art partnership',
    trend: [72.0, 74.5, 76.8, 77.6, 78.9, 79.6],
    signatureWork: { title: '최후의 만찬', titleOriginal: 'The Last Supper', artist: '쩡판즈', artistOriginal: 'Zeng Fanzhi', year: 1995, priceUsd: '약 2,330만 달러', priceKrw: '약 303억 원', note: '아시아 현대 미술 붐을 이끈 「가면」 연작의 핵심 대작', auction: '2013 소더비 홍콩',
      meaning: '최후의 만찬 구도를 빌려, 붉은 스카프를 맨 가면 쓴 인물들이 수박을 나누는 장면으로 바꿔 놓았습니다.',
      intent: '「가면」 연작은 급속한 도시화 속에서 개인이 쓰게 되는 사회적 가면을 주제로 합니다. 붉은 스카프와 노란 넥타이의 대비가 이념에서 자본으로의 이동을 암시합니다.',
      cityLink: '1990년대 중국의 시장경제 전환과 신흥 컬렉터 계층의 등장을 압축합니다. 상하이가 아시아 현대미술 시장의 가속 장치가 된 시기와 정확히 겹칩니다.',
      image: imgShanghai },
  },
  {
    slug: 'singapore', code: 'SIN', name: 'Singapore', nameKo: '싱가포르', country: 'Singapore', latitude: 1.3521, longitude: 103.8198,
    index: 76.8, type: 'ASEAN Gateway Hub', typeKo: '아세안 관문 허브', dna: 'Regional access · Global finance',
    insightKo: '역내 접근성과 글로벌 금융이 결합합니다. 아세안 컬렉터 프로그램과 다문화 예술 플랫폼이 적합합니다.',
    signalScores: { market: 78, cultural: 73, opportunity: 80 },
    market: { artists: ['Chua Ek Kay', 'Zhuang Guanbin'], priceRange: '8K–1.5M', currency: 'USD', status: 'indicative' },
    cultural: { institutions: ['National Gallery Singapore', 'SAM', 'ArtScience Museum'], events: ['Art SG', 'Singapore Art Week'], keywords: ['ASEAN access', 'financial hub', 'multicultural'] },
    industry: ['Finance', 'Tech', 'Hospitality'], opportunity: 'ASEAN collector programme · multicultural art platform',
    trend: [72.5, 73.8, 75.0, 74.4, 75.9, 76.8],
    signatureWork: { title: '정물화 (두리안이 있는)', titleOriginal: 'Still Life with Big Durian', artist: '조젯 첸', artistOriginal: 'Georgette Chen', year: 1965, priceUsd: '약 170만 달러', priceKrw: '약 22억 원', note: '싱가포르 난양 화파의 선구자 · 동남아 소재와 서양 후기 인상주의의 결합', auction: '2023 크리스티 홍콩',
      meaning: '두리안과 열대 과일을 놓은 정물로, 동남아 고유의 소재를 서양 후기인상주의의 색과 붓질로 다룹니다.',
      intent: '파리와 상하이를 거쳐 싱가포르에 정착한 첸은 지역의 삶을 정물로 기록하며 「난양 화파」의 시각 언어를 만들고자 했습니다.',
      cityLink: '싱가포르 난양 화파의 정체성이 형성되는 지점에 놓인 작품입니다. 내셔널 갤러리 싱가포르가 이 계보를 동남아 미술의 정전으로 세우고 있습니다.',
      image: imgSingapore },
  },
]

export function listCities(): readonly City[] {
  return cities
}

export function findCity(slug: string): City | undefined {
  return cities.find((city) => city.slug === slug)
}

export function rankCities(): readonly City[] {
  return [...cities].sort((a, b) => b.index - a.index)
}
